### ISSUE TITLE
Replace Buttons/IconButtons with the new Button/IconButton component

### ISSUE THREAD

**Issue by hanapotski** [hackforla/food-oasis#1000]
### Overview
We want to use the Button from the UI library

### Action Items
- [x] Use the `Button` and `IconButton` components from the UI library
- [x] Make sure the app still works
- [x] Verify it looks the same as before

**Comment by dking1342** [comment]
I have updated the template Button and IconButton components. I created an index file in the UI folder for easier access so that everything can be exported from that file. I included the Input component in the UI folder as well. I replaced all button, iconbutton and textfield in the codebase as per the vscode search. Awaiting a merge and pull

**Comment by dking1342** [comment]
After further work, the UI Index file has been updated to not include a Controls object. Now each affected file in the codebase has been changed to reflect the template element from the UI Index file. Next template element to implement in typography
