### ISSUE TITLE
Localization support, allowing new cities/regions to customize and localize Food Oasis instances

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1003]
Why:
Because regions such as Hawaii are starting up their own local Food Oasis websites, we should build-in the ability to customize the website for each region without having to fork the project.

What:
Native support for custom logos, page content, landing page images (which will soon be a map of the service area) for each region.

One way to solve this may be: a config file for each region, pointing to logos, page content (About us, FAQ, etc.), and other localizations.  Similar to how language localization works for text strings.

**Comment by Benbaillou** [comment]
Hi - could we please size the project with a dedicated label. Thanks

**Comment by fancyham** [comment]
@entrotech I think we do this already — perhaps this issue can be closed?!

**Comment by staceyrebekahscott** [comment]
@entrotech Following up on Bryan's question from April, and confirming what you explained to me in Slack re: how the Hawai'i Food Oasis site works, has everything in the Overview for this issue been completed?

**Comment by itserindean** [comment]
following up on "perhaps this can be closed" as of 8/17/22 I noticed all the non LA versions of our site still use the LA about/FAQ/Donate.
[la.foodoasis.net](https://la.foodoasis.net/) or [foodoasis.la](https://foodoasis.la/) - Los Angeles County
[ca.foodoasis.net](https://ca.foodoasis.net/) - Areas of California outside of LA County
[hi.foodoasis.net](https://hi.foodoasis.net/) - The Hawaiian Islands
[sb.foodoasis.net](https://sb.foodoasis.net/) - Santa Barbara County
[mckinney.foodoasis.net](https://mckinney.foodoasis.net/) - McKinney, TX

**Comment by staceyrebekahscott** [comment]
@itserindean The Food Oasis sites are set up as a multi-tenant application that share the same code base. They have the ability to change what is on the static pages, the About/FAQ etc. But the reason the LA info is on there is because the other sites don't  have dedicated teams regularly supporting them to create this locally relevant content. I have made inquiries into the Hawai'i site, and Santa Barbara may be one that we can also reengage with. But for now the LA content, while not ideal, is the option there is. 

Given the focus on the LA site for the Impact Sprints, addressing the "sister" Food Oasis sites should be a medium/ long term goal.

**Comment by staceyrebekahscott** [comment]
Closing this issue. Building a process for the other Food Oasis sites is a long and large undertaking, and will be a goal once we have figured out all of the design and volunteer workflows for the LA Site.

**Comment by fancyham** [comment]
This issue can/should be closed because the site already supports customizing logos and static pages for different regions.
