### ISSUE TITLE
Organization ID | remove "other" category

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1154]
### Overview

To avoid confusing the Food Seekers with too many details displayed on the listing panel and the detail panel

1. organisation identification should be limited to one category only
2. category "Other" should be removed as it does bring any value 

### Action Items

**Admin Panel**
- [ ] See the feasibility to withdraw "Other"

**Map and listings**
- [ ] Re-design the detail panel and the listing panel to add more space between categories and the other texts - Designer
 
### Resources/Instructions
Admin Panel
![Capture d’écran 2022-01-19 à 17 36 23](https://user-images.githubusercontent.com/91577998/150187370-a4565adb-006d-4054-a041-2c0293dbe23c.png)

Detail Panel
![Capture d’écran 2022-01-19 à 17 37 03](https://user-images.githubusercontent.com/91577998/150187419-6729371a-be88-4c88-8f9b-ceb780215707.png)

Listing Panel
![Capture d’écran 2022-01-19 à 17 37 42](https://user-images.githubusercontent.com/91577998/150393991-ac6a7197-30fd-495b-97f6-b78df3694967.png)

**Comment by staceyrebekahscott** [comment]
Moving to Icebox, to be reassessed after October when the Impact Sprints 2022 are complete.

**Comment by entrotech** [comment]
The application only shows listings that are food pantries and/or meal programs, though the admin screens allow one or more of a dozen or so categories to be assigned to a listing.  This allows the admins to record listing that have previously been verified as belonging to several different categories - including categories that are not displayed to food seekers.  This is helpful when we are searching various 3rd party lists of listings, so we can make sure we don't waste time validating suggested listings that were previously determined not to be a meal program or pantry.

Previously, if a listing was a Food Pantry or Meal Program AND one or more other categories, it would be shown to food seekers, listing all of the categories assigned to it. So a listing might be shown to users as with categories of "Meal Program, Shelter" or "Food Pantry, Other".  So the question raised by this issue is whether we should show all the categories of a listing.  We definitely need to show whether a listing is a Meal Program and/or Food Pantry, but IMO, it is also useful for a Food Seeker to also know if a listing is also a Shelter, Care Program and/or Food Bank, as it might influence their decision about which location to choose.  Other categories are, IMO, not useful to food seekers (at least at this time), like Community Gardens, Supermarkets, and especially Other or Don't Know. So I chose to implement this feature using a pre-existing column is_for_food_seekers on the Category table to specify which categories should be displayed to food seekers, and populate the column with "true" for Meal Program, Food Pantry, Care Program, Food Bank and Shelter categories, so these are the only categories displayed in the food seeker UI.
