### ISSUE TITLE
Design System update

### ISSUE THREAD

**Issue by sei1122** [hackforla/food-oasis#1204]
### Overview
We need to update the **Design System** to design more efficiently. When I’m designing, I refer to the design system color, font, button, and components. Some of the items are not the latest so I need to back and forth website and design system.  

### Action Items

- [ ] Review the current design system with the team
- [ ] Audit Food Oasis site
- [ ] Update design
- [ ] Approval by team

### Resources/Instructions

Currently, there are 2 versions of the design system.

**Design System version 1**
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=0%3A1

<img width="683" alt="Screen Shot 2022-04-22 at 6 10 58 PM" src="https://user-images.githubusercontent.com/19811032/164845894-7f8cf921-d339-4db9-b3b2-196fe1cd7404.png">

 **Design System version 2**
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=0%3A1
<img width="628" alt="Screen Shot 2022-04-22 at 6 11 31 PM" src="https://user-images.githubusercontent.com/19811032/164845980-6a93686d-c6bf-49b7-8b3c-e661b132f5db.png">

Material UI (React library) is used Food Oasis site. This is helpful when we design. 
**Material UI** 
https://www.figma.com/community/file/912837788133317724

**Comment by fancyham** [comment]
From our meeting with @entrotech 
- Programmers are using color palettes from figma
- Anything more involved than that, even when designers create CSS, that CSS usually only works on one device and at once size…
- but actually programmers have to make it work on all devices and browsers which requires tweaking and things like that.

Often Figma specs or figma font sizes don't translate to the web smoothly, perhaps due to CSS issues.

Is there a way for designers to work in a way that developers can easily use and recreate designs?

John: 
- Not that unhappy with the current process.  Good practice for developers, too, since this is very real-world problem.
- Not sure we can do much better than where we are now
- Perhaps we can design to three different responsive breakpoints?

Bryan: 
- Is there a design/dev environment that previews CSS well that can be used by programmers?

**Comment by staceyrebekahscott** [comment]
@sei1122 Can you review this issue and its updates and reassess the priority for me in your opinion? If it is impacting your ability to design more efficiently should this be made more of a priority, or can it be closed if the current system is working well enough for most people on the team?

**Comment by sei1122** [comment]
If we have 4 designers on our team, I'd like to do it because more people are affected to create for design, and nice to have the standard. If not, we can wait.

**Comment by staceyrebekahscott** [comment]
@sei1122 OK. Thanks for your assessment. I'll leave the issue where it is for now and once we have more designers we can move this up in priority.

**Comment by fancyham** [comment]
In the Figma, we have two 'style guides' listed which is definitely confusing.  From my understanding:

The first one is a style guide of colors, fonts, etc. from 2020

The other "Style guide v2" is from from 2021, and was, I think, intended to be defining new proposed styles, but due to time constraints morphed into an audit of styles currently in-use on the site in May 2021, and showing those vs proposed changes.

To make this more clear, I renamed the two Figma pages to:
2020: Style guide
2021: Audit of styles in-use and V2 proposal

**Comment by staceyrebekahscott** [comment]
@sei1122 Will completing issue #991 also resolve this issue? Please explain how they are related and if they can/ should be combined.

**Comment by sei1122** [comment]
I work on #991 to focus on Typography, Color, and Logo consistency with the Dev team. 
After completing #991, we can move on to this issue. Either I or another designer can work this.

**Comment by staceyrebekahscott** [comment]
[Design System Planning- Google Sheet](https://docs.google.com/spreadsheets/d/1OqrFDOet1N0JZ3PgUAat8_pjaNFCAJMPmP8ZU4IE3oI/edit?pli=1#gid=0)

@jnaito777 @nkiwan Assigning this issue to you. You can use this as a starting issue or Epic, and link any issues you create to this one. It is in the Prioritized backlog for now, but you can move it to In Progress whenever you are ready to get started on it.

**Comment by sei1122** [comment]
We break down the design system issue into more small tasks, so I close this issue.
