### ISSUE TITLE
Upgrade to Material UI 5.8

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1239]
### Overview
The application currently uses @material-ui version 4.12.  The current version is @mui/material@5.8.3. Upgrade the app to the new major version.  It seems to be a radical upgrade and will be challenging.

### Action Items
- [ ] Read up on how to migrate to the new version.
- [ ] Upgrade and debug
- [ ] Test, test, test!!

**Comment by staceyrebekahscott** [comment]
Sent John a question on combining this issue with #1045 and reassessing priority.

**Comment by staceyrebekahscott** [comment]
None of the current milestone fit what this issue addresses. Once new milestones have been approved, will update accordingly.

**Comment by staceyrebekahscott** [comment]
@fancyham @sei1122 Can you advise how this might fit into our roadmap along with the design changes being planned? Is this something that needs to be done before we proceed with any more design changes? Same for Issue #1238.

**Comment by sei1122** [comment]
I think not affected by to design side much. 
The roadmap is Website improvement? or creating a new milestone that is a Dev-focused issue that has no dependency on other teams.

**Comment by staceyrebekahscott** [comment]
@entrotech @sei1122 @fancyham My question here is will the design work that is being planned be affected by upgrading to this version of Material UI. Meaning design work might not be able to be worked on if this new upgrade needs to be tested and debugged, thus creating delays in our schedule/ roadmap goals. I am not fully clear on what Material UI is so I am also asking for more of an explanation of what the upgrade actually entails. 

1.  What is Material UI?
2. What is the actual work that needs to be done to upgrade to 5.8? 
3. How urgent is this upgrade? 
4. How will it affect the design work (will work need to be stopped in order to test and debug the upgrade)?

**Comment by fancyham** [comment]
From what I've read, 5 might make styling easier and improve site responsiveness.  

@staceyrebekahscott info about Material UI.  It's a framework that makes creating React UIs easy with standardized UI components.  https://mui.com
