### ISSUE TITLE
Remove one of duplicate similar icons

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1278]
Problem:
The two similar icons on the same area are kind of distracting. 

Severity 1 - Cosmetic problem only: need not be fixed unless extra time is available on project

Heuristics Violated:
8:  Aesthetic and minimalist design

Recommendations:
It would be good to delete one of these icons. 

### Action Items

- [ ] Design team proposes which should be removed 
- [ ] Design mocks up how it would look
- [ ] make change as designed

Note: the issue in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0) (item no. 31) asks to link this to #1131 

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by sei1122** [comment]
We discussed the team and we decided to remove the icon because it isn't useful. 
You can see the updated version at
https://devla.foodoasis.net/ 

Next release and it should be updated. 

<img width="472" alt="Screen Shot 2022-08-10 at 5 26 31 PM" src="https://user-images.githubusercontent.com/19811032/184045165-f56e98d3-a71c-4d04-8ef9-e252a67eebb0.png">

I think we can close this issue

**Comment by itserindean** [comment]
duplicate of #1153
