### ISSUE TITLE
Bug: Food Seeker page not loading on Mac Safari 

### ISSUE THREAD

**Issue by yiminng** [hackforla/food-oasis#1300]
#### Describe the bug 

Search function does not work on Mac Safari site 

#### What's the expected result?
to have map or listing show up 

#### What's the actual result?
Search error 

#### Additional details / screenshot
- Video recording (https://user-images.githubusercontent.com/109191409/185315333-fe8c74cf-9199-4b95-94ae-c5603a646ae4.mov)

#### Device configuration
- Device: [Desktop computer]
- OS version: [OS 10.15.7]
- Browser [Safari]
- Browser version [14.0]

**Comment by entrotech** [comment]
@yiminng I have a MacBook running MacOS Monterrey 12.5.1, and I'm able to run Food Oasis with no problem on Safari 15.6.1. It seems like your network is OK, since you are getting the location drop-down to show choices, which requires your internet to work, so I'm not sure what the issue might be.  I will poll the other devs and see f anybody has a Mac and can reproduce your issue.

**Comment by sei1122** [comment]
I have Macbook Air and I tested the site on Safari. It worked on my end.

**Comment by staceyrebekahscott** [comment]
I just tested this on my iMac on Safari and also got a search result error. Said there was no listings available in my area. I am running older OS and Safari versions so that might account for the error on my end.
