### ISSUE TITLE
Remove Footer from Application

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1302]
### Overview
The footer, including the Logo and main menu items is considered redundant throughout the application.  Remove it (except for the widget footer, which provides branding when FO is embedded on 3rd party sites.

### Action Items
- [ ] Remove the footer (circled in the screenshot)

### Resources/Instructions
![image](https://user-images.githubusercontent.com/9939032/185519503-8782b4e1-cff9-42ef-936b-4798e3e5be5f.png)

**Comment by staceyrebekahscott** [comment]
@entrotech As per the team meeting discussion, the issue here was that the hamburger menu did not disappear for all of us when scrolling up and down the page. For those who had it disappear, they found it useful to have the menu on the bottom. 

And when testing it again, I noticed that the hamburger did disappear on the About Us page, but it stayed on FAQ, Donate. and Suggest New Listings. I'm using Chrome on an iMac. 

What might explain that inconsistency?

**Comment by staceyrebekahscott** [comment]
Approved issue and moved to Prioritized Backlog.

**Comment by staceyrebekahscott** [comment]
This issue was created based on our conversation during the team meeting, but there was already a Heuristics issue in the Waiting Column- #1289 . Closing issue #1289 as more notes have been made on this issue.
