### ISSUE TITLE
The foodoasis.la domain expires on 9/7/22. Transfer needs to be initiated by 8/31

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1310]
### Overview
Historically, we have used the foodoasis.la domain. It is hosted on hover.com, but cannot be renewed there, since Hover no longer supports the "la" top-level domain.  This is probably due to the fact that the la top-level domain is technically for the country of Laos. Though other sites in Los Angeles have also used this TLD in the past, I suppose it is considered bad form to hijack Laos' TLD for our purposes.  We transitioned to using the foodoasis.net domain, and all of our current sites are available as subdomains of foodoasis.net. In particular, the Los Angeles County site is currently accessible from foodoasis.la or la.foodoasis.net.

The main problem with letting the foodoasis.la domain expire is that current users may have it bookmarked, and some partners have linked it on their websites. For example Food Forward is linked to this URL on https://foodforward.org/food-for-individuals/. It is also used by our social media accounts.

### Action Items
- [x] Decide if we want to find a new host and pay for the domain foodoasis.la
     - [x] we do
     - [ ] we do not
- [ ] if so, find a new host and get the hosting set up.
     - [x] research registrars
     - [ ] choose new registrar
     - [ ] transfer registration
     - [ ] get hosting set up 
- [ ] If not, try to track down places where we are referenced, and get those links updated.
- [ ] This may involve some sort of change to our cloudflare setup as well.

### Resources/Instructions
Here is a partial list of web sites that reference foodoasis.la:

- https://www.latech4good.org/news/foodoasis
- http://publichealth.lacounty.gov/eh/LACFRI/share-donate.htm
- https://la2050.org/organizations/food-oasis-los-angeles
- https://foodforward.org/food-for-individuals/
- https://twitter.com/foodoasisla
- https://www.ffwd.org/tech-nonprofits/s/food-oasis/
- https://geohub.lacity.org/datasets/lahubcom::los-angeles-public-food-access-sites/about  (This site publishes our data, and attrributes the data to us.)

**Comment by staceyrebekahscott** [comment]
@ExperimentsInHonesty Bonnie- how do the domain purchases work with HfLA? And do you have any advice as to how we should handle this situation?

**Comment by itserindean** [comment]
@entrotech  Did this happen early? I'm getting an Error 1016 DNS error for foodoasis.la as of this afternoon.

**Comment by staceyrebekahscott** [comment]
@itserindean I just checked and the domain is working now. Not sure why that Error came up before.

**Comment by itserindean** [comment]
@entrotech Can you clarify if hover.com will no longer renew registration AND no longer host? As I've been researching I've found some providers that can not handle registration for .al sites but will host if we register elsewhere.

**Comment by itserindean** [comment]
on 8/25 at our team meeting we agreed we should find a new registrar and continue to support the .la domain for the time being due to how many partners link to that site which represents about 15% of our incoming traffic to the site (According to [google analytics for the site](https://drive.google.com/file/d/19rI8EVEkehYj5O_Lmu41Ap1Ji0f6w4Qd/view?usp=sharing))

I put together [this research]([url](https://docs.google.com/spreadsheets/d/1pyiPueqeJlfBopJOZDYBxR-2s_8JCwQKqgLgkFljZzU/edit?usp=sharing)) with options for sites that we can transfer registration to.

![Screen Shot 2022-08-28 at 9 24 26 AM](https://user-images.githubusercontent.com/107142453/187084327-4549b6e6-ed67-4609-8549-d7f387bbe56c.png)

The best value I've found is Porkbun. And while I've never heard of them before, they are generally [well reviewed.](https://tld-list.com/registrars/porkbun) (Reviews go back 6 years. when i sorted by date I noticed that in the past year reviews are less favorable.

**Comment by itserindean** [comment]
Also I noticed that some sites will not transfer domains within 7 days of expiration which give us a soft deadline of August 31 to make a change. 3 days

**Comment by ExperimentsInHonesty** [comment]
@itserindean Message seen.  Looking into it now.

**Comment by ExperimentsInHonesty** [comment]
I have started the transfer but I am not sure its going to work.  Because some of the requirments we can't seem to meet. Let's see how it goes


Here is the info from inside porkbun
![image](https://user-images.githubusercontent.com/37763229/187452868-4f2ef04e-72ce-48a8-a892-c9f17d0c28b6.png)




Posting this here for discussion purposes
[Querying whois.nic.la]
[whois.nic.la]
Domain Name: FOODOASIS.LA
Registry Domain ID: D34481107-LANIC
Registrar WHOIS Server:
Registrar URL:
Updated Date: 2021-03-30T17:56:26.0Z
Creation Date: 2016-09-07T03:28:23.0Z
Registry Expiry Date: 2022-09-07T23:59:59.0Z
Registrar: EPAG domainservices GmbH
Registrar IANA ID:
Domain Status: ok https://icann.org/epp#ok
Registrant Email: https://whois.nic.la/contact/foodoasis.la/registrant
Admin Email: https://whois.nic.la/contact/foodoasis.la/admin
Tech Email: https://whois.nic.la/contact/foodoasis.la/tech
Name Server: AMIT.NS.CLOUDFLARE.COM
Name Server: RUTH.NS.CLOUDFLARE.COM
DNSSEC: unsigned
Billing Email: https://whois.nic.la/contact/foodoasis.la/billing
Registrar Abuse Contact Email: abuse@centralnic.com
Registrar Abuse Contact Phone: +49.2283296840
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2022-08-30T13:14:56.0Z <<<

**Comment by ExperimentsInHonesty** [comment]
info from current registrar hover
![image](https://user-images.githubusercontent.com/37763229/187453136-78f3dade-851f-422c-beec-8eb5bcbeb445.png)


Owner/admin/tech email: foodoasis@hackforla.org
billing: travis@hackforla.org (no one uses that account at HfLA anymore, we should have changed it long ago.  If it requires a confirmation, I can log into the account and take control of it, and then change it).

**Comment by ExperimentsInHonesty** [comment]
@itserindean @entrotech  It looks like it might go through.  Here is the email I got from Hover
![image](https://user-images.githubusercontent.com/37763229/187474309-bae1f20d-56b4-4893-af01-a4aacbe348b2.png)
I will still need to log into porkbun and buy extra years (I can't do that until its transferred).

**Comment by itserindean** [comment]
@ExperimentsInHonesty Thanks for all of the updates!

**Comment by entrotech** [comment]
@ExperimentsInHonesty @itserindean As far as I can tell, it seems to still be in progress.  I tried the transfer myself to day, but ran into problems because the transfer was already in progress. The account password for Porkbun in the 1password vault wasn't correct, so I had to reset it again 0 and updated the vault with the new password. When I was going through this, there was a message that the transfer must be completed before the renewal can be ordered - we'll need to check back in a day or two to see what the expiration date is after the transfer.

**Comment by itserindean** [comment]
I checked the whois today and is shows an expiry date in April of 2023. So it seems like the transfer has gone through. I think we can close this issued, @entrotech  do you agree? 

![Screen Shot 2022-09-04 at 4 26 14 PM](https://user-images.githubusercontent.com/107142453/188337530-574cc39b-c2ed-47b5-8ab6-b26c7dda21af.png)
https://www.godaddy.com/whois/results.aspx?checkAvail=1&tmskey=&domain=https%3A%2F%2Fwww.hackforla.org%2F

**Comment by entrotech** [comment]
The above whois search is for hackforla.org.. It appears that everything went through - A whois lookup today shows this:

![image](https://user-images.githubusercontent.com/9939032/188973930-84f7bcdc-a87a-4dd8-9681-c2b5691e6745.png)

In the course of the transfer, they transferred the cloudflare nameservers as well, so Cloudflare is being used for traffic that comes through foodoasis.la (but not for the *.foodoasis.net domains), and the expiration is Sept 7, 2023.

**Comment by itserindean** [comment]
Thanks @entrotech Not sure how I failed to catch such a fundamental error. Thank you for checkin in on this today.
