### ISSUE TITLE
Bug: Suggest a listing feature not emailing submission

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1409]
#### Describe the bug 
When an individual submits a suggestion of a food pantry or meal program via the suggest a listing feature no notification email is sent.

#### Steps to reproduce the issue

1. Go to 'foodoasis.la'
2. Click on 'hamburger menu'
2. Click on 'suggest a listing'
3. Fill out form and submit
4. No email is received at foodoasisinfo@hackforla.org

#### What's the expected result?
email with suggestion is sent to foodoasisinfo@hackforla.org

#### What's the actual result?
unknown

**Comment by entrotech** [comment]
@staceyrebekahscott @itserindean In response to the question "What is happening with these suggestions?":

The suggestions are stored in a table in the database. Admins can use the "Suggestion" Menu item to open the Suggestion Admin page.  At this time, they can filter to see the various suggestions by their status, and they can change the status to indicate whether the suggestion has been rejected or accepted. It is up to the Admin to make any required edits or create new organizations and manage the statuses.  @sei1122 spent quite a bit of time developing a workflow for Admins to manage Corrections (changes to existing listings, initiated by the Correction button on listing details) and Suggestions (the Suggest a New Listing menu option available to anyone). This was Issue #1131. It was approved by the PMs (@staceyrebekahscott ) and I created Issues #1373, #1271, #1272, #1273 to START on the flow for Corrections. Issue #1373 is done and #1271 in progress, 
Anecdotally, Greg Pawin from Lucky Parking has mentioned that he submitted a Suggested new listing a few times, but it has not been processed to show up in the application.

Rylan Telerico added comments to #1272 and #1273 that imply he wanted to revisit the priority for these issues. IMO, this is probably an over-engineered feature for something that may not be used very often, so that might be what he was thinking. 

Since then @itserindean has gained much more experience with the Admin and Volunteer roles and should probably weigh in on the importance and design of the workflow before we put in too much effort.

**Comment by entrotech** [comment]
We generally have not implemented email notifications to Admins for anything - the thinking is that it would be annoying and generally not a good way to track what needs to be done and who is doing it. I'd imagine that it would be like the volunteer edit approval workflow, where the admin periodically checks and dispositions the pending suggestions and corrections from the suggestion admin screen, so we can keep track of what is complete, rejected, and still pending.

**Comment by itserindean** [comment]
Closing since this was never intended behavior.
