### ISSUE TITLE
Decide on a design for Standard Buttons

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#1518]
[Food Oasis Development Website](https://devla.foodoasis.net/login/)

[Standard Button styles](https://github.com/hackforla/food-oasis/blob/develop/client/src/components/UI/StandardButton.js)

### Overview
The design of Buttons in the application is quite varied. Decide on a standard design and behavior. Identify specific instances where the standard button is not appropriate and define what deviations from the standard are desired.

### Background
The development team is in the process of organizing the code such that the design of various components is consistent across the  application. This should provide a more consistent user experience in terms of control appearance and behavior. Should we deciee to change the behavior or appearance of a control, we should theoretically only need to change it in one place in the code, and all instances of that control will be updated throughout the application.

This issue addresses the standardization of buttons. To get started, we used roughly the type of button that appears\ed on the Organization Detail Panel as the standard:
![image](https://user-images.githubusercontent.com/9939032/213546552-cc61a5b3-418c-4982-b3d1-61e9d8bcab30.png)

In the program code we created a "standard button" component and are replacing almost all the buttons in the application with this standard component.  You can experience this, for example by running the application in the development environment (https://devla.foodoasis.net) and looking at the Organization Detail Panel or the Login Form.  We'll use the Login Form as an example. The appearance of the button changes depending on it's state:

Normal:

![image](https://user-images.githubusercontent.com/9939032/213547613-925d384e-8005-4782-ab04-acf0db5cb1bb.png)

With keyboard focus:

![image](https://user-images.githubusercontent.com/9939032/213548119-bb424db4-cc29-41e4-a09d-a2c5c014ab6f.png)

Disabled (in this case because there are validation errors on the form):
![image](https://user-images.githubusercontent.com/9939032/213548348-b4189c7e-2521-4817-b394-34dc133efbb9.png)

and Hover:

![image](https://user-images.githubusercontent.com/9939032/213548521-b75d6313-3511-4456-9f6d-2268c9392a65.png)

This is largely the behavior that designers specified for the Organziation Detail Panel after much discussion (except that they did not identify a keyboard focus appearance - I used the default Material Design hover behavior for the standard for now until we can agree on an alternate behavior that makes sense).

Most buttons in the application have already been converted to this standard.

However, there are situations where the standard behavior is probably not best:
In some cases, the background is dark and the standard colors will not provide enough contrast.  Though we could customize such exceptions for each button instance, it MIGHT make sense to define a "second standard" button that is suitable for display on dark backgrounds.
Some buttons are "toggle buttons" like the PANTRIES and MEALS filter buttons on the Map Page (and the Map/List button that alos appears on the Map Page on small devices). These have an additional state of "on/off" and we could therefore have a standard toggle button design specification. Right now, there are only a few such buttons and their behavior involves specific colors and icons, so it's not clear if standardizing the toggle buttons is important.

### Action Items
- [x] Complete audit of application and Login form in the dev environment, noting deviations from the standard buttons ([Figma file](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=640%3A106&t=gXvdQ0YHrSj7ylmU-0) for audit)
- [x] Review all the buttons in the application and see if we should have alternate specifications for specific situations, such as rendering on a dark background, and propose additional "alternate" standards - identifying the situations where they should be applied.
- [x] If there are buttons that specifically deviate from the standard(s) button, explicitly identify them and review their appearance and behavior.
- [x] Review the proposed "standard" button behavior and appearance as you see on the Login form in the development environment. Decide on any changes that you want to make to the design appearance and behavior, and create a development issue describing the changes. This should also be incorporated in the Figma design specification as the standard button.
- [ ] Work with dev to beta test on dev site (designers, researchers, PMs should review it for usability — suggested: 3-5 people to review)

 > - [ ] https://github.com/hackforla/food-oasis/issues/1618

- [ ] Release updated version

**Comment by staceyrebekahscott** [comment]
@itserindean Added this to In Progress on Product board, as John D wants this to be a priority.

@naraedesigns Adding you to this issue and adding this to In Progress on Project management board.

See notes on Design team agenda: [Design Team Meeting Agenda](https://docs.google.com/document/d/1oLPGqa2DX0tvGLc2F3mN1xqmMjZurUYd4-AKkMj4bWI/edit#) and [Leads/PM Meeting](https://docs.google.com/document/d/1uPO0_AJ1zn3IZXrhHBXub-ZfakIsx34jKHK3LIB8VmM/edit#): Leads/PM Meeting

**Comment by entrotech** [comment]
@sei1122 Seiko made a good point in last Thursday's meeting about the buttons.  It's common to have "Primary" and "Secondary" buttons, where a Primary button is visually more pronounced and is used for the most likely, i.e., primary Call-to-Action on a page, where Secondary buttons are used for less likely CTA's.  For example the Login and Registration pages have a single Primary CTA. The Verification Admin page might have the Query button as a Primary button and the buttons above the grid as Secondary CTA's.

**Comment by naraedesigns** [comment]
- Completed audit of buttons on dev/testing site.
- Sent the Figma file to John and design system team (James, Natalie, Seiko).

**Comment by naraedesigns** [comment]
### Button Audit of Application

![Screen Shot 2023-01-30 at 3 18 30 PM](https://user-images.githubusercontent.com/86501066/215618598-f68fa9d4-6e37-44bb-8846-7d38277e263c.png)

![Screen Shot 2023-01-30 at 3 18 50 PM](https://user-images.githubusercontent.com/86501066/215618651-44101afc-dd75-4190-81af-12bafc4fdaf8.png)

![Screen Shot 2023-01-30 at 3 19 06 PM](https://user-images.githubusercontent.com/86501066/215618698-62cac733-1ccb-418c-ac7e-d873aec720ed.png)

![Screen Shot 2023-01-30 at 3 19 32 PM](https://user-images.githubusercontent.com/86501066/215618771-d3a103a5-2a70-4dd7-a97b-2f488b8d8b85.png)

![Screen Shot 2023-01-30 at 3 19 48 PM](https://user-images.githubusercontent.com/86501066/215618824-ff5e22e7-1b3c-4ae9-9b15-5d724c8531c1.png)

**Comment by naraedesigns** [comment]
### 1/25/23 Button Audit of Login/Backend

![Screen Shot 2023-01-30 at 3 21 15 PM](https://user-images.githubusercontent.com/86501066/215619061-7d30c262-bc05-4708-8506-2a6a13ce62d9.png)

![Screen Shot 2023-01-30 at 3 21 29 PM](https://user-images.githubusercontent.com/86501066/215619089-5349d19c-23cb-427f-8834-c2525af5b5c9.png)

![Screen Shot 2023-01-30 at 3 22 28 PM](https://user-images.githubusercontent.com/86501066/215619216-9ebac2d8-916f-46cc-bb72-1980ce664f2c.png)

![Screen Shot 2023-01-30 at 3 22 42 PM](https://user-images.githubusercontent.com/86501066/215619247-c971415e-83f4-4b79-8a20-8b98d7491567.png)

![Screen Shot 2023-01-30 at 3 22 55 PM](https://user-images.githubusercontent.com/86501066/215619272-4c541144-4e60-4d4d-ab2b-2f5391c49cb8.png)

![Screen Shot 2023-01-30 at 3 23 06 PM](https://user-images.githubusercontent.com/86501066/215619307-d6348b3e-4d38-441b-aeb5-62337b496fdc.png)

**Comment by naraedesigns** [comment]
### 1/26/23 John's comments in Slack

I don't want to undermine Narae's audit of the site's buttons, but I made another pass through the application and created PrimaryButton and SecondaryButton components and took my best guess at applying them to the different buttons in the application.  One or the other of these should be applied to every button in the application except for the following "custom" buttons on the Map page: Re-center, Meals, Pantries and Map/List (on Mobile only).

There really should only be two different types of buttons now, the one that starts out with a blue background (primary) and one that starts out with a white background and a border (secondary).  It might be easiest to look at the "Send Correction" Dialog, since it has both a primary (Send) button and a secondary (Cancel) button. The Send button on this page exhibits the normal, disabled, hover and keyboard focus states, and the Cancel button exhibits the normal, hover and keyboard focus states (but not disabled), so this form covers most of the combinations of button type and state.
An example of a disabled secondary button can be seen on the Verification Admin screen - the Needs Verification buttons will be a disabled Secondary button until one or more rows are selected.

It theoretically shouldn't be necessary to study the behavior of every button on the site. If we just make sure these few examples work as you want, then all the others SHOULD work as well, unless we devs accidentally overrode a style accidentally.  The design of the primary and secondary buttons is just by preliminary guess based on what was already there - I'll leave it up to you to refine how each button should really look.

This revised version is on the development environment now. I'm hoping it will dramatically reduce the number of different combinations the UI/UX team needs to design to just two (and I suppose, the fours custom buttons at some point).

Narae also had a number of other good observations noted in the Figma file - such as cases where submit buttons should be disabled until there is valid input, etc.. I'll need to review all of these and will create dev issues for ones that aren't already addressed.

**Comment by naraedesigns** [comment]
### 1/30/23 Update
I reviewed John’s examples of the PrimaryButton and SecondaryButton components on the dev site. 

I created a “primary and secondary” button guide with suggestions, and shared it with design systems team and Bryan for design feedback. I will send it to John after revising it based on team feedback.

**Comment by naraedesigns** [comment]
### 1/30/23 Button Guide (suggested changes)

For comparison's sake, I first created a button guide of the current buttons. 
![Screen Shot 2023-01-30 at 3 28 25 PM](https://user-images.githubusercontent.com/86501066/215620037-8f874d96-213b-418d-b654-6cc31ee0c007.png)

Then I created a button guide with suggested changes.
![Screen Shot 2023-01-30 at 3 28 57 PM](https://user-images.githubusercontent.com/86501066/215620120-f011011c-7611-4009-8490-1895aabb1409.png)

I wrote out the suggestions separately to make it easy to see.
![Screen Shot 2023-01-30 at 3 29 41 PM](https://user-images.githubusercontent.com/86501066/215620220-d6a9c7c0-5296-4ce2-af71-9562aa917da4.png)

I added some additional thoughts.
![Screen Shot 2023-01-30 at 3 30 03 PM](https://user-images.githubusercontent.com/86501066/215620271-337a4a8f-751f-415f-887a-c7c225454c5d.png)

**Comment by naraedesigns** [comment]
### Team feedback on V1 of button guide - 1/30/23

Source: Figma comments

- Seiko and Bryan provided feedback - mainly that the colors looked too similar to default button, also hovered, focused, pressed button states look very similar. MUI was provided as a reference. 
- Bryan's suggestion: "with dev help (or if you’re comfortable doing it yourself) you can try out these styles on the dev site and play with, test, and adjust them before it goes live on the public site."

- I asked how important it is to the team that I follow a set standard, i.e. like Material Design, or is it more flexible to just choose whatever color works best? 
- Seiko's answer: "The guide helps to learn industry standards. So it is good to look at them. They have a vast library and are very systematic, which is good but sometimes the rule is overwhelming for small sites. We can decide what works for us. Material design uses opacity to control the states. We can talk about whether we want to use opacity or solid colors at the meeting (2/1). Also, we can ask John D’s opinion."

**Comment by naraedesigns** [comment]
### 2/1/23 Button Guide V2.1 and V2.2

I made changes to the hovered, focused, pressed states of the primary button based on team feedback in Figma. 

[Button guide V2.1](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=1665%3A830&t=KSq8G4iTyX6ZiAH1-0)
<img width="1107" alt="Screen Shot 2023-02-01 at 4 36 39 PM" src="https://user-images.githubusercontent.com/86501066/216201915-9dbeb47f-9f12-4fcf-a14a-517e7184eb9d.png">

[Button guide V2.2](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=1665%3A927&t=KSq8G4iTyX6ZiAH1-0)
<img width="1128" alt="Screen Shot 2023-02-01 at 4 36 54 PM" src="https://user-images.githubusercontent.com/86501066/216201938-1c1d4991-b987-4411-a117-96973e302661.png">

**Comment by naraedesigns** [comment]
### 2/1/23 Team meeting 

- Participants: John, John, James, Seiko, Natalie, Narae
- I presented V2.1 and V2.2 and explained the main difference is using opacity or solid color for the fill of the primary button (hovered, focused, pressed states). Also the solid color version has a darker fill.
- I asked John about what's technically easier; John noted, “we can do anything, just tell us what you want."


- I also received the following feedback: 
- Majority of folks preferred the button color of V2.2 because it’s easier to distinguish the darker color from the default (enabled) button color.
- There was a concern about animation effect for the focused and pressed states, as the animation currently loops indefinitely. People who are using the keyboard to navigate may stay on a button for longer, which is a risk as animations can potentially trigger seizures for some people.

**Comment by naraedesigns** [comment]
### Button Guide_V3 (2/2/23)

I made changes based on team feedback from the 2/1/23 meeting. 

[Button guide_V3](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=1717%3A627&t=QG2xEaoEhLlNCmRr-0)
<img width="1368" alt="Screen Shot 2023-02-02 at 9 18 46 AM" src="https://user-images.githubusercontent.com/86501066/216395972-92d9cda2-6755-4246-88dc-cb98309101bf.png">

[V3 Suggestions List](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=1717%3A746&t=KraEjKOwji4VD6YP-0)
<img width="873" alt="Screen Shot 2023-02-02 at 9 19 14 AM" src="https://user-images.githubusercontent.com/86501066/216396073-e59091c0-a6da-4df3-9078-425598208884.png">

Follow-up 

- I shared this V3 with James, Natalie, Seiko, Bryan and let them know that I would ask for feedback from the design team as a whole and check in with Bryan to see if he's down to sign off on this version.
- I shared it also with John to keep him in the loop, with the caveat that this document is **not finalized**, and that I'll let him know when it has Bryan's approval to move forward.

**Comment by fancyham** [comment]
Progress looks good, @narae-ux — sounds like you've been getting good feedback along the way, too.

I added some notes to the v3 designs:
- See if you can get primary and secondary focus states to look related (i.e. both with bolded borders, or both with that animated circle, etc.)
- It'd be great if you could show primary and secondary buttons against both light and dark backgrounds (so 4 variations) so folks can more easily look at the variations.
- I added a couple of next steps to the overview above — an opportunity to work with devs and to see your work live:
  - [ ] beta test new styles (work with an dev on this) on the dev site
  - [ ] do a usability/look-and-feel review (3-5 testers from different backgrounds would be ideal) and any revisions if needed
  - [ ] Coordinate with devs to launch (might be part of a larger update)

**Comment by narae-ux** [comment]
### Team feedback from 2/2/23

Source: Design team meeting

- Briefly discussed the decision to remove the animated pulsating effect for focused states re: possibility of the pulsating effect triggering seizures or other negative physical reactions

- Suggestion (preference) for focus state - glow / outline instead of pulsating effect
- IBM / Carbon Design System was provided as a reference
- Focus state has an outline inside of the button, same color as default button
- Hover state is a slightly darker color
- Pressed is the darkest color
- Suggestion: hovered and focused states are the same color, pressed state is a darker color
- Secondary buttons overall - outline is not easy to see, suggestion to try out different widths, i.e. 2px or 3px width
- Radius overall - suggestion to try out a slightly bigger radius, but not fully rounded, i.e. a capsule

Action items
- [ ] Reached out to John to coordinate / ask about timeline - completed 2/2/23
- [ ] Reached out to dev leads John and Hannah to request a demo page, to try out different button colors and styles before it goes live on the public site - completed 2/2/23

**Comment by narae-ux** [comment]
### Button Guide_V4 (2/3/23)

I made changes based on team feedback from the 2/2/23 design team meeting. 

[Button guide_V4](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=1839%3A922&t=UCxIe9VELIfyxoBf-0)

V4.1 - Changes based on team feedback
<img width="1269" alt="Screen Shot 2023-02-03 at 9 40 41 AM" src="https://user-images.githubusercontent.com/86501066/216670774-5e582d46-896a-4cfc-8c46-e093cba2f171.png">

V4.2 - Radius increase only (from 4 to 8)
<img width="1287" alt="Screen Shot 2023-02-03 at 9 41 07 AM" src="https://user-images.githubusercontent.com/86501066/216670848-86ceb136-f568-483d-983d-a9797ef22d79.png">

V4.3 - Radius increase only (from 4 to 12)
<img width="1304" alt="Screen Shot 2023-02-03 at 9 41 32 AM" src="https://user-images.githubusercontent.com/86501066/216670934-483926b1-ded4-42ff-9359-e1bf0893024e.png">

[V4 Suggestions List](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=1839%3A1309&t=UCxIe9VELIfyxoBf-0)
<img width="751" alt="Screen Shot 2023-02-03 at 9 38 55 AM" src="https://user-images.githubusercontent.com/86501066/216670388-0c8c2e76-aa54-496a-97b7-fa671da96691.png">

Follow-up 
- I shared this V4 with the design team via the group slack channel and tagged Bryan, James, Natalie, and Seiko specifically. I reminded them I'll be away for a week and requested feedback by EOD today, otherwise I will follow up once I return.

**Comment by narae-ux** [comment]
Button Guide_V4 (2/3/23)

I shared this V4 with the dev leads John and Hannah and let them know I'll be away until 2/15 and requested feedback by EOD today, otherwise I will follow up once I return.

**Comment by narae-ux** [comment]
I shared latest update of the button guide (V4) with dev leads John and Hannah, and informed them I'll be away until 2/15 and will follow up when I return. I let them know they can reach out to the design team as needed, in the meantime.

**Comment by narae-ux** [comment]
2/16/23 

I followed up with Hannah and John (dev leads):
- I asked for specific release date so I can align with their timeline; right now I know it's sometime in March.
- I asked again if either one (or someone from dev team) would be able/willing to help set up a demo page so designers can try out different styles for buttons to see what it looks like before deciding on final styles for button components.

**Comment by narae-ux** [comment]
### Update 2/24/23
- Provided the following update in slack: I was out sick recently so wasn’t able to make progress on this issue, but I’m better now and my goal is to finish this next round of iterations (V5) by next Thursday 3/2. My end goal is to have a final design by 3/8, about one week before the release date (mid-March), and get real user feedback to make sure it’s ready to be shipped. 
- Tagged design lead (Bryan), dev lead (John), the rest of the design systems team (Seiko, James, Natalie)
- Reached out to John to ask for his preferred communication style so we can stay in sync

### Feedback - 2/23/23
Source: Design team meeting

- Buttons look too big
- Button radius is too round - maybe go back to original or increase only a little from original
- Font size looks bigger than text
- Padding is too much
- Multiple borders may be causing issues, i.e. double outline may be shifting things on the screen, sometimes it’s extra space - try highlight / glow as Bryan mentioned previously


### Feedback - 2/3/23
Source: Figma comments

- Increase button corner radius from 4 to 8 - this option got 2 votes
- The double-outline (reference: IBM design system) for secondary focused button is “pretty unfamiliar-looking”  — suggestion to try a single thicker outline and/or a light glow/dropshadow to make it distinct even on a dark background 
- Suggestion to check to see how different browsers render focus state

**Comment by narae-ux** [comment]
### Button Guide_V5 (completed 3/2/23)
I made changes based on team feedback from the 2/23/23 design team meeting.

[Button guide_V5](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=2214%3A2340&t=mTShektSKTj10eZI-0)

V5_Button Guide
![Screen Shot 2023-03-02 at 5 14 14 PM](https://user-images.githubusercontent.com/86501066/222606876-cb89f950-4cec-4041-94e6-113910614438.png)

V5_List of Changes
![Screen Shot 2023-03-02 at 5 15 04 PM](https://user-images.githubusercontent.com/86501066/222606978-c28fb893-9582-439f-926d-e80f6a8bb567.png)

Quick visual comparison for easy reference
![Screen Shot 2023-03-02 at 5 17 50 PM](https://user-images.githubusercontent.com/86501066/222607275-322f72a2-4dac-452a-9ac5-86f3065e96a0.png)

=======

Also shared a few issues/inconsistencies I found on the dev site:
![Screen Shot 2023-03-02 at 5 15 59 PM](https://user-images.githubusercontent.com/86501066/222607085-ddf146a9-c1b3-4919-9243-eae46304effc.png)

![Screen Shot 2023-03-02 at 5 16 11 PM](https://user-images.githubusercontent.com/86501066/222607101-55769e3e-2871-4a03-a309-911bdcbd9b6d.png)

And asked a question on the public/live site:
![Screen Shot 2023-03-02 at 5 16 26 PM](https://user-images.githubusercontent.com/86501066/222607134-d66d0a79-2ee7-48e4-a054-13ed21334a58.png)

**Comment by narae-ux** [comment]
I also cretaed a quick mockup to show the dev team a rough preview of what the buttons (V5) will look like live on the public site, and placed a button component on a screenshot of the live site so that people can play around with it and preview the design live. I added quick instructions so people can try out all the different states of the button component.

![Screen Shot 2023-03-02 at 5 22 29 PM](https://user-images.githubusercontent.com/86501066/222607772-01a49412-6c1e-49a2-87bb-b2c5eca2e96a.png)

**Comment by narae-ux** [comment]
### Team feedback from 3/2/23
Source: Design team meeting

I presented V5, with brief context for previous version, during the design meeting and explained rationale for changes. The team provided positive feedback that the design looks good. Bryan noted "it's hard to tell without seeing it on the site, but it looks like it’s going in the right direction."

Action items
- [ ] Ask dev team to implement it on the dev site to preview it
- [ ] If I have time, look into Figma’s prototyping function to quickly mock up what buttons look like live

**Comment by narae-ux** [comment]
### Reviewing button style on mobile

I determined the button style on mobile looks good and works fine as it is currently, after reviewing both primary and secondary buttons on different iPhone screen sizes using screenshots and Google Chrome’s dev tool.

[Buttons on mobile](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=2280%3A2647&t=ZiiUctjXypNKqwaZ-0)
![Screen Shot 2023-03-06 at 3 40 45 PM](https://user-images.githubusercontent.com/86501066/223281657-6e02b2c7-a2cc-49c4-a316-b404d783943a.png)

**Comment by narae-ux** [comment]
### Call with John - 3/9/23

Participants: John, Narae
Purpose: I met with dev lead to request feedback on the new button design (V5) and ask to implement it on the dev site, also ask questions on timeline and breakpoints.

- Implementation of V5 on dev site: John finished the implementation today, so we reviewed it together on the call. He noted minor issues he’s aware of and working on: buttons shift slightly when pressed, also the dropshadow is not showing.
- Timeline: John noted timeline is flexible, dev team is looking to finish a few issues first before release to production. 
- Breakpoints: John said we’re technically using MUI default breakpoints, but realistically we’re working with two screen sizes, below 600px (for mobile devices) and above 600 px.

Action items
- [ ] Usability testing

**Comment by narae-ux** [comment]
### Button Guide_V6 (completed 3/13/23)

I made changes based on team feedback, and also added in icons as they are a key part of buttons but I had overlooked them previously. 

[Button guide_V6](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=2458%3A2560&t=Iu9fKAytm0qo383s-0)

V6_Button Guide
![Screen Shot 2023-03-13 at 8 39 05 PM](https://user-images.githubusercontent.com/86501066/224887200-a9ab1f2a-cc2a-46cd-b0ac-6ad67bd101cc.png)

[Button Specs_V6](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=2458%3A2961&t=Iu9fKAytm0qo383s-0)
![Screen Shot 2023-03-13 at 8 40 15 PM](https://user-images.githubusercontent.com/86501066/224887359-b46d5803-f5a4-4e16-b71d-b3f12393fb47.png)

Follow up:
- I tagged each member of the design systems team with a question on their respective area - Seiko for color, James for iconography, Natalie for typography, to maintain alignment across our design system. 
- ![Screen Shot 2023-03-13 at 8 41 06 PM](https://user-images.githubusercontent.com/86501066/224887463-e68dc2de-07e9-4134-bb34-66d4d5a6535a.png)

- I also asked our dev lead John if he turn off MUI’s handling of focus state, as I'm making the recommendation to use the browser default for platform consistency - as a follow up to Bryan's helpful feedback. Also noted to John that it appears the button styles are the same across a wide range of screen sizes, i.e. mobile and desktop, and look and work fine. Recommended keeping it as is for now - with flexibility to make changes as needed.

Action items:
- [ ] Share this update with the design team via slack, ask for feedback
- [ ] Prototype buttons
- [ ] Usability testing

**Comment by fancyham** [comment]
Some feedback from me — the new buttons still seem too big compared to the body text of the listings on this screen. My eyes go to the buttons before the names of the orgs, for example.  

Perhaps the text size has increased too much?  If so, suggest using the original font size to keep the same relative font sizes.

Left side is new version, right side is old:
<img width="1366" alt="Food Oasis" src="https://user-images.githubusercontent.com/3376957/227073384-d82601aa-8c6f-41ca-90dc-cf8939660881.png">

**Comment by sei1122** [comment]
This sends the suggestions button is low contrast. 
Disable button color should be #949494 background + #FFFFFF text color according to Narae's design. 

<img width="1202" alt="Screen Shot 2023-03-22 at 9 11 45 PM" src="https://user-images.githubusercontent.com/19811032/227101389-2d56388f-aab6-4f82-ae34-4106fb44ce6d.png">

**Comment by narae-ux** [comment]
### Slightly revised Button Guide (V6.2)

[Button Guide V6.2](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=2835-3679&t=W14TTjKTJ6pmAQdX-0)
![Screen Shot 2023-04-03 at 3 55 24 PM](https://user-images.githubusercontent.com/86501066/229644102-2eb78cd6-fbee-467e-9b1b-009d93ea0d43.png)

It also includes Button Design Guidelines
![Screen Shot 2023-04-03 at 3 54 16 PM](https://user-images.githubusercontent.com/86501066/229643963-8c1cad5e-1a9d-4dee-832e-e845f1ecf36b.png)
![Screen Shot 2023-04-03 at 3 54 31 PM](https://user-images.githubusercontent.com/86501066/229643988-47791b33-6f11-4126-912f-504ac5df42cf.png)

[Implementation Review](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?node-id=2835-4186&t=W14TTjKTJ6pmAQdX-0)
![Screen Shot 2023-04-03 at 3 57 42 PM](https://user-images.githubusercontent.com/86501066/229644414-568cbd8e-a710-4efc-8a18-471717e295a1.png)

Changes to be made 
- All secondary buttons, font-size: 13px/0.8125rem
- Secondary button, pressed state only, box-shadow: inset 0px 8px 4px rgba(51, 102, 153, 0.24)
- Primary button, pressed state only, box-shadow: inset 0px 8px 4px rgba(0, 0, 0, 0.24)
@entrotech thank you in advance!

**Comment by entrotech** [comment]
In the Button Design Guidelines, under Typography and Content, it says buttons are all 14pt, but in the Button Specifications it says, primary button font is 16px for Desktop, 14 pt.0.875 rem for mobile, and secondary button font is 13px/0.8125rem for desktop and mobile. I implemented the latter.

I added the horizontal margin between the two buttons on the Verification Dashboard.

I can't find the Mobile background color mentioned above as being #A4A4A4

In the Implementation Review for Buttons above, I assume that specifying the Secondary Button Disabled state background color as #949494 is an error and it should remain as white, as Specified in the Button Specs section of the Figma file. Otherwise, the color, background-color and border-color would all be the same.

There isn't really a way to specify the gap between icon and text on a button as part of the button style - it will need to be specified for each case where an icon and text appear on a button.
