### ISSUE TITLE
Update Styling System to Use sx Prop in Material-UI Components in StaticPagesMCK/About.js

### ISSUE THREAD

**Issue by 93Belen** [hackforla/food-oasis#1844]
### Overview
Our project currently utilizes the makeStyles function for styling Material-UI components. However, with the updates in Material-UI version 5, it is recommended to transition to using the sx prop for styling. 
Additionally, once we don't use the makeStyles function, we will be able to remove the `mui/styles` dependency, which has conflicts with React v.18 recently added to our project. 
This GitHub issue is part of a series of Issues aiming to update the styling system in our project. In this issue, we are going to update Update Styling System to Use xs Prop in Material-UI Components in `/components/StaticPagesMCK/About.js` 

### Action Items
- [x] Replace HTML elements with Material Ui components
- [x] Replace the existing makeStyles implementation with the sx prop for styling.
- [x] Ensure that the changes do not impact the styling overrides in the theme folder.
- [x] Make sure you don't lose accessibility when replacing semantic HTML for Material UI Components
- [x] Add Before and After screenshots to your PR

### Resources/Instructions
https://mui.com/material-ui/getting-started/overview/
https://mui.com/material-ui/migration/migration-v4/

**Comment by andyarensman** [comment]
Rather than matching the design of the old MCK About page, I made it match the current LA About page. This included updating the section icons and the partner logos.

Old MCK About:
![chrome_FsZ46BU4Cg](https://github.com/hackforla/food-oasis/assets/86622025/1cc5e437-a2fd-4d7c-8e22-5b0c02e0aba9)
![chrome_1XbD52FhT6](https://github.com/hackforla/food-oasis/assets/86622025/f4876cd6-ea72-4424-af66-93232154f438)

Current LA About:
![chrome_9zknXVEJH9](https://github.com/hackforla/food-oasis/assets/86622025/d24ab99e-f46d-4d0e-96b2-6bf8c478339b)
![chrome_dzc1z1RshV](https://github.com/hackforla/food-oasis/assets/86622025/a9fdb91d-b568-4911-9c1f-bf8d44e7e658)

New MCK About:
![chrome_UEq5TcCLNE](https://github.com/hackforla/food-oasis/assets/86622025/295cd013-4e09-41ac-b6ee-875ff1e7f10b)
![chrome_l6EHyIUnLP](https://github.com/hackforla/food-oasis/assets/86622025/ed8164c0-44ea-4aad-8284-fccaf8556858)
