### ISSUE TITLE
Update Styling System to Use sx Prop in Material-UI Components for Static Pages SB (About.js) 

### ISSUE THREAD

**Issue by junjun107** [hackforla/food-oasis#1845]
## Overview
Our project currently utilizes the makeStyles function for styling Material-UI components. However, with the updates in Material-UI version 5, it is recommended to transition to using the sx prop for styling. In this issue, we are going to update About.js in SB. 

FO is a multi-tenant web application for websites in several different geographic areas:

[la.foodoasis.net](https://la.foodoasis.net/) or [foodoasis.la](https://foodoasis.la/) - Los Angeles County 
[hi.foodoasis.net](https://hi.foodoasis.net/) - The Hawaiian Islands
[sb.foodoasis.net](https://sb.foodoasis.net/) - Santa Barbara County
[mck.foodoasis.net](https://mck.foodoasis.net/) - McKinney, TX

### Action Items

- [x] Change tenantId in client .env to 6 to switch to SB
- [x] Replace HTML elements with Material Ui components
- [x] Replace the existing makeStyles implementation with the xs prop for styling.
- [x] Ensure that the changes do not impact the styling overrides in the theme folder.
- [x] Make sure you don't lose accessibility when replacing semantic HTML for Material UI Components
- [x] Attach screenshots of before and after in PR
- [x] Change tenantId back to 1 before push 

Check ticket #1721 for reference

**Comment by andyarensman** [comment]
- Closes #1845 

Rather than matching the design of the old SB About page, I made it match the current LA About page. This included updating the section icons and the partner logos and adding the footer. The "(TBD)" placement looks weird right now, but when it is replaced with paragraph text, it will look right.

Old SB About
![chrome_ygAgIoJFml](https://github.com/hackforla/food-oasis/assets/86622025/e5c3e7c6-8872-4232-a042-5e18de3a4838)


Current LA About:
![chrome_9zknXVEJH9](https://github.com/hackforla/food-oasis/assets/86622025/d24ab99e-f46d-4d0e-96b2-6bf8c478339b)
![chrome_dzc1z1RshV](https://github.com/hackforla/food-oasis/assets/86622025/a9fdb91d-b568-4911-9c1f-bf8d44e7e658)

New SB About:
![chrome_dPoQN2nnU1](https://github.com/hackforla/food-oasis/assets/86622025/0797a3bf-709e-44d0-b815-6e9b54b7dc19)
![chrome_T7Ek06HTyg](https://github.com/hackforla/food-oasis/assets/86622025/74d36cc2-90eb-49f8-aca4-8734f739f524)
