### ISSUE TITLE
Update Styling System to Use sx Prop in Material-UI Components in StaticPagesMCK/Faq.js

### ISSUE THREAD

**Issue by 93Belen** [hackforla/food-oasis#1847]
### Overview
Our project currently utilizes the makeStyles function for styling Material-UI components. However, with the updates in Material-UI version 5, it is recommended to transition to using the sx prop for styling. 
Additionally, once we don't use the makeStyles function, we will be able to remove the `mui/styles` dependency, which has conflicts with React v.18 recently added to our project. 
This GitHub issue is part of a series of Issues aiming to update the styling system in our project. In this issue, we are going to update Update Styling System to Use xs Prop in Material-UI Components in `/components/StaticPagesMCK/Faq.js` 

### Action Items
- [x] Replace HTML elements with Material Ui components
- [x] Replace the existing makeStyles implementation with the sx prop for styling.
- [x] Ensure that the changes do not impact the styling overrides in the theme folder.
- [x] Make sure you don't lose accessibility when replacing semantic HTML for Material UI Components
- [x] Add Before and After screenshots to your PR

### Resources/Instructions
https://mui.com/material-ui/getting-started/overview/
https://mui.com/material-ui/migration/migration-v4/

**Comment by andyarensman** [comment]
Rather than copying the MCK Faq style exactly, I used the LA Faq styles. I also added the Footer. The text looks like it should be updated - it references LA instead of MCK.

Old MCK FAQ:
![chrome_qwwJAbmAZP](https://github.com/hackforla/food-oasis/assets/86622025/00c8c42b-d459-43aa-bd8c-15b152b20808)
![chrome_9qI4KK8MG7](https://github.com/hackforla/food-oasis/assets/86622025/d3752a4f-e641-4d64-a075-01f347374450)

Current LA FAQ:
![chrome_0XDMyXgJDG](https://github.com/hackforla/food-oasis/assets/86622025/cb4254ff-ae46-4509-b586-278b01d42675)
![chrome_ySwfsIFFcw](https://github.com/hackforla/food-oasis/assets/86622025/33f6819a-0f2e-433c-8e58-0235b3965761)

New MCK FAQ:
![chrome_TyB0aNQbMu](https://github.com/hackforla/food-oasis/assets/86622025/2741c849-c3d0-453f-bb5b-52b39e32f66c)
![chrome_Yrrdva4Bt0](https://github.com/hackforla/food-oasis/assets/86622025/66d66bab-ade2-405a-911c-1a133496ce0c)
