### ISSUE TITLE
FOLA's  META Title and META Description Update

### ISSUE THREAD

**Issue by Shienny1** [hackforla/food-oasis#2196]
Difficulty: Pretty easy -- might be a good first or second issue for a dev.
Importance: Helps improve our google search ranking, adds description for our page for searchers and when bookmarking.

### Overview
To increase FOLA's click through rate  (CTR), we need to update our META title and META Description in the HTML on our web pages.  These META descriptions are used by search engines and helps people find our pages.

More info: https://developers.google.com/search/docs/crawling-indexing/special-tags

Current META Descriptions does not compel action, so this would improve our search engine ranking (i.e. this is SEO search engine optimization)

### Action Items
Creating effective call-to-action-type (CTA) META descriptions for foodoasis.la pages involves combining a concise summary of the content with a compelling call-to-action that encourages users to click through.

- [x] Add these `<meta name="description" content="A description of the page">` tags to our various web pages
- [x] Please alert @Shienny1 and @fancyham when you're done so we can review

**1. Homepage / Landing Page:**
META Title:  Food Oasis
META Description:
"Discover local free food resources with Food Oasis LA. Find food pantries and free meal programs near you. Click to start finding free food today!"

**2. Find Food page:**
META Title:   Food Resources Directory
META Description:
"Search our comprehensive directory for food pantries and community kitchens in LA. Get the support you need. Access free food resources now!"

**3. About Us Page:**
META Title: About Us
META Description:
"Learn about Food Oasis LA and our mission to connect Angelenos with local food resources. Discover how we’re fighting hunger in LA. Find out more now!"

**4. Donate Page :**
META Title: Get Involved
META Description:
"Support food security in LA. Your donation helps us connect more people with the food they need. Click to donate and make a lasting impact today!"

**6. Contact Us Page:**
META Title: Contact Us
META Description:
"Have questions or need assistance? Contact Food Oasis LA today! We’re here to help connect you with local food resources. Reach out to us now."

**5. Volunteer Login:**
META Title: Join Our Team
META Description:
"Make a difference in your community! Volunteer with Food Oasis LA to help connect people with food resources. Sign up today to start helping those in need."

###**Below is a description for a possible additional page I would like to propose (needs review and approval)**
(if this page has been approved, also add this meta tag)

8. *Blog or News Page:
META Description:
"Stay informed with the latest news and updates on food security in LA. Explore our blog for tips, stories, and insights. Click to read more today!"

Note: Contents for this Blog page is in planning, then , review and approval.

![Image](https://github.com/user-attachments/assets/a7d0ed76-4b1a-425b-a5e4-832a27dd7fae)

The image attached is the current META Description.

### Resources/Instructions
Tips for Writing CTA (call-to-action-type) META Descriptions:
- **Include a CTA:** Encourage users to take action by using verbs like "discover," "find," "sign up," "donate," "learn," or "explore."
- **Be Concise:** Keep the description under 155-160 characters to ensure it displays fully in search engine results.
- **Highlight Benefits:** Clearly communicate what the user will gain by clicking through.
- **Use Keywords:** Incorporate relevant keywords naturally to improve search engine visibility.

**Comment by fancyham** [comment]
@Shienny1 - for the META Title -- I'm not familiar with the Meta Title attribute, but if you're referring to the "Title" attribute of the web page (which is what shows up in the tab or window name, and in bookmarks), I think we should have something like:

Web page title: "Food Oasis - Contact Us" instead of 
META Title : "Contact Us" only.  

Why?  So FOLA tabs are easier to identify and so that they bookmark nicely.  If you agree, could you change the description above?  Or let's discuss!  Thx

**Comment by fancyham** [comment]
(Let me know either way -- will send it to devs when we've addressed that part.)

**Comment by Shienny1** [comment]
@fancyham RE: META TITLE : "FOOD OASIS- Contact us " is OK
Meta Titles typically are limited to 50-60 characters but I think we are good.

**Comment by fancyham** [comment]
I see now - meta 'title' is different from the page title -- https://stackoverflow.com/a/21076220

> The first is to display page name.
> 
`> <title> This will be displayed in the title bar of your Browser. </title>
`> Second is for crawling.
> 
`> <meta name="title" content="Whatever you type in here will be displayed on search engines.">
`

So you're saying:
```
<head>
  <title>Food Oasis - Contact Us</title>
  <meta name="title" content="FOOD OASIS">
  <meta nane="description" content="Discover local free food resources with Food Oasis LA. Find food pantries and free meal programs near you. Click to start finding free food today!">
</head>
```

Google's recs for meta descriptions:
https://developers.google.com/search/docs/appearance/snippet

Some SEO guy's recs for meta titles:
https://www.teamlewis.com/magazine/seo-metadata-best-practices-on-page-optimization/#:~:text=Meta%20Title%20SEO%20Best%20Practices&text=A%20good%20meta%20title%20should,quickly%20understand%20the%20page's%20content.

So for the meta titles, perhaps we could add a bit to it so that it appears in the large blue google links in their search results... something like "Food Oasis - A Free Food Pantry & Meals Map"?

**Comment by Shienny1** [comment]
NOW I am confused what's difference between META TITLE and Description. 
I think DESCRIPTION is most important- because, per your research, it is 
<meta name="title" content="Whatever you type in here will be displayed on search engines.">

SO I think anything other than what we have currently is better  ( please see attached) - almost every single page has the same description.

<img width="566" alt="Screenshot 2024-09-21 at 2 09 48 PM" src="https://github.com/user-attachments/assets/2ab23886-3546-49ac-85e2-f77bd3ad4dcf">

**Comment by fancyham** [comment]
👍 Mind if I make some suggested edits to the descriptions?  Suggestions here:

https://docs.google.com/document/d/15zAFDDqLBrkN8URX7HdeZU7rVmFgfRwDt_gwJx1CPx4/edit

What do you think?  I added in words like 'free' in a few places and changing 'community kitchen' to 'free meals', changing the web page titles in similar ways to what you suggested above for Meta Title, and also pulled back a little on some promises that I think we're not set up to handle (just yet).
