### ISSUE TITLE
Follow up on the data verification issues and provide overall status on 1/21/2020

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#236]
### Overview
We need to have a weekly record of what team progress, Blocks, Availability & Eta to completion for each volunteer and for the project as a whole.

### Action Items
Bonnie added a request for an update to each of the in progress issues on the [Data Verification Board](https://github.com/hackforla/food-oasis/projects/8)

@chombus 
1. Please review Nat's comments and mine on this issue, and the note I left for you, and coordinate with me after you have surveyed the team to find out if you have a spanish speaking resource. https://github.com/hackforla/food-oasis/issues/197
2. Please reach out to each person personally, ask them to complete their update.  Please do not do it for them:
    - Here is the person we have heard nothing from: [Lucas](https://github.com/hackforla/food-oasis/issues/191) 
    - Here is someone we heard something from but we need a weekly update since he estimated he would be complete by 1/17: [Nicholas](https://github.com/hackforla/food-oasis/issues/204)
    - Here is a person who answered 1 of the 4 questions asked: [Tina ](https://github.com/hackforla/food-oasis/issues/201)

@chombus & @jpmikesell 
On this issue, it is pointed out that sometimes they ask us to call back.  Do we have a script for asking if there is someone we can email, when we are calling back a second time?  And do we have a script already setup for that? Gabby's issue - https://github.com/hackforla/food-oasis/issues/196

**Comment by jpmikesell** [comment]
Spoke to Chris and Natesh about how to merge scraped data with open source data verification tool. Nat has found one. Need to discuss it. He also suggested some other tools to help us that he used in his company.

I forsee a group merging the data that will later be verified by volunteers. Volunteers will be recruited on social media, on a webinar and also somehow in groups. I believe we need several ways to verifiy this data. 

Beofre all of the data is verified, I'd like to go live somehow with the verified data we have at this time. How can we seperate the verifed data and getting it up live for us to test it with users? Since we don't have a staging site, maybe we can up load the site here.

**Comment by chrislopez28** [comment]
Follow-up on Open Source Tools:
* Checked out the RPA tool Roro. It looks like a potential non-coding option to do scraping, however I wasn't able to get a workflow started on my PC. This could be something to explore in other Hackforla projects. However, as we already have webscrapers in Python and Javascript for fola, I don't think we need this.

* I dl'ed the dataprofiling tool however wasn't able to get it to connect to the Postgres database. I will give it a try again later after we have some more progress on scraping and combining data.
