### ISSUE TITLE
Decide on UI for Multiple Selection and "Other"

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#315]
The figma file Jenny and Gaby created as a concept for the Organization Edit Screen has a few data fields (Languages, Types of Food, and Services) where they want to allow the user to select from a list of standard choices, but also allow them to free-type one or more ad hoc entries as well. We need to design and implement a control for such data. 
We should find a better UX that:

- is consistent
- allows for a fairly long list of standard options without taking too much screen real eestate
- is easy for the user to understand and hard (prefereably impossible) for them to use incorrectly
- allows for efficient data entry with a minimal number of clicks and keystrokes

### Action Items
- [ ] Conceptualize UX ideas with wireframes
- [ ] Choose a design
- [ ] Implement a custom react component to realize the design
- [ ] Integrate the control with the Organization Edit form for the three data fields mentioned above.

### Resources
This is similar to Issue #316, but without the addtional feature of being able to add a note to each selected option

![image](https://user-images.githubusercontent.com/9939032/80403320-472df700-8874-11ea-86d4-ebb673655107.png)

![image](https://user-images.githubusercontent.com/9939032/80403369-56ad4000-8874-11ea-95b9-986790ce227e.png)

![image](https://user-images.githubusercontent.com/9939032/80403424-67f64c80-8874-11ea-8995-fbd2bd296071.png)

**Comment by staceyrebekahscott** [comment]
@fancyham @sei1122 Is this issue still relevant? It was created in April 2020 and no work has been done on it. 

Please advise if this can be closed out.

**Comment by sei1122** [comment]
This is the same as #315 so we can close.

**Comment by sei1122** [comment]
We haven't done it for 2 years so we can close this.

**Comment by staceyrebekahscott** [comment]
As per Seiko's comment, closing this issue.

**Comment by fancyham** [comment]
Yes, this is closed.   To add some history here:
After talking with entrotech, we decided that checkbox fields were too constraining for most things right now and rather than create an ontology of checkboxes and fields that work in one region but not another, we should continue to use freeform text, with the idea that in the future, we’d like to add text and keyword search and may add a more free-form tagging system in the future.

This is somewhat related to #947 (Advanced search/filtering) since these would be used for those filters.
