### ISSUE TITLE
Implement the "Suggest an Edit" Feature.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#327]
### Overview
Our goal is to provide the most accurate comprehenisve data possible about food resources. We should allow users to let us know when any information published on the site is inaccurate or misleading. This issue is to decide how to implement a feedback process that is simple and encourages end users to help us with this and processes their feedback for efficient follow-up by FOLA personnel.

### Action Items

- [ ] Conceptualize a process for users to let us know when information is incorrect. We need to know exactly which organization they are referring to, and decide how detailed their feedback needs to be (maybe just free-form text suggestion, or perhaps a way for them to click on information they beleive to require re-verification).
- [ ] Come up with a process for FOLA personnel to process this feedback. Flags attached to organization entries, or maybe a running queue of suggestions across all stakeholders that can be viewed and checked off as complete when done.
- [ ] Maybe an email response to suggestions thanking the user for their help and/or notifying them when their suggestion has been processed?
- [ ] Create design and development issues to implement this feature.

**Comment by lizagarrison** [comment]
TBD for MVP, assigning it to that milestone now because it's definitely a "nice-to-have" but hasn't been included in our MVP reqs thus far

**Comment by entrotech** [comment]
Development fast-tracked this feature on Issue #624 to get something in production. I'm leaving this issue open to review the design and perhaps make it look better.

**Comment by sei1122** [comment]
@entrotech, @fancyham, @staceyrebekahscott 
We can close this issue since we have
- Send Correction
- Suggest a New Listing (https://www.foodoasis.la/suggestion)

<img width="597" alt="Screen Shot 2022-08-08 at 10 17 43 AM" src="https://user-images.githubusercontent.com/19811032/183475811-e33def65-48c2-46d8-a1a0-e3247027b5b4.png">
<img width="926" alt="Screen Shot 2022-08-08 at 10 18 42 AM" src="https://user-images.githubusercontent.com/19811032/183475970-18e5c1cd-03da-404d-90e2-14a88c33dc98.png">

**Comment by staceyrebekahscott** [comment]
As per Seiko's comments, closing this issue.
