### ISSUE TITLE
Modify Verification Dashboard

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#368]
### Overview
Make Changes to the Verification Dashboard

### Action Items
- [x] Change "Verification Dashboard" to "My Dashboard" on Main Menu
- [x] Change "Verification Dashboard" to "[User's Name]'s Dashboard" for the page caption on the verification dashboard
- [ ] Records should be divided into two sections - ""Current Assigned Organizations"" and ""Submitted for Review"" (users cannot change anything in the records already submitted for review - maybe the organization name would not be a link to the OrganizationEdit form?)

- [x] For ""Current Assigned Organizations"", users should be able to see the following information as columns in the grid::
a. Organization Name
b. Date Assigned
c. Org Email
d. Org Hours
e. Org Address
f. Org Phone
g. Org Category"

### Resources/Instructions
Link to [email feedback from volunteers](https://docs.google.com/document/d/1pTa0JNedIizFtz7aCfRMVkvwd_DYCsK5SI_8_AaULFE/edit?usp=sharing)
[Issue for UX Research for dashboard](https://github.com/hackforla/food-oasis/issues/903)
[User flow PDF](https://drive.google.com/file/d/1g64nt3S0FgQDp2yHeugPEny481nrKh4R/view?usp=sharing)
[User flow slides](https://docs.google.com/presentation/d/1y6O7ghU-YmCD-oEJBBe2cDcz2cyy5HP1fAmYRP_ouJk/edit?usp=sharing)

**Comment by entrotech** [comment]
Should they be able to see
- verification status
- critical field % complete
- six critical field check boxes
?

**Comment by jpmikesell** [comment]
Volunteers need to see on their dashboard (I want to try this new order):
ID
Name
City
Status - Submitted - Approved
Perm
Covid
Name
Address
Phone
Email
Category
Hours
Assigned Date
Submitted Date
Approved Date

**Comment by entrotech** [comment]
As of 3/23/21 this issue is somewhat stalled. The best wireframe we have for a proposed change can be found in the [Dashboard Redesign](https://www.figma.com/file/KZbof1x83FOvw4Jfc99EIf/Food-Oasis-Dashboards?node-id=521%3A67) figma file on the page called "Volunteer Dashboard" - referring to the wireframe labeled "Volumnteer Dashboard - v12". This was orginally done by Robin Yumena based on direction from Jenny and perhaps some other people. The left-hand main menu shown is not really part of the dashboard. Jenny's plan was to finalize this design with UX/UI people and then proceed to do UX testing with experienced volunteer users based on some sort of clickable prototype, before finalizing and specifying and issue for development.

The idea of including a "to do" list is based on the observation that volunteers almost always end up creating their own to do list in the process of trying to process their assignments.

IMO, this might need considerable discusson with Admins and Volunteers to converge on a design that would be a good step forward from their existing dashboard.

**Comment by ktjnyc** [comment]
Link to feedback from Jordan - 
[Meeting Notes](https://docs.google.com/document/d/1s15-xkos4LM175a4CjIEr8ZUageov1hqjr1MkarjYtQ/edit?usp=sharing)

**Comment by ktjnyc** [comment]
Based upon the 3/25 meeting next steps are:

Link to [email feedback from volunteers](https://docs.google.com/document/d/1pTa0JNedIizFtz7aCfRMVkvwd_DYCsK5SI_8_AaULFE/edit?usp=sharing)
[Issue for UX Research for dashboard](https://github.com/hackforla/food-oasis/issues/903)

- [ ] Review & group volunteer feedback into functional groupings 
- [ ] Identify the possible development options
- [ ] Identify what we we want to move forward to 
- [ ] Work to identify Liza's business process diagram for this work (may identify the pain points of volunteers are having)
- [ ] @erigilg add comments to this issue on things she identified by watching the Saturday volunteer onboarding

**Comment by erigilg** [comment]
These are the notes and feedback I have of the research volunteer onboarding: 

- Screenshots are not up to date (the actual website is different form some screenshots in the presentation)
- It would be good to add an email example to the script: “Hello, I just wanted to follow up and find out if this location is still offered as a food pantry to the public? And if so, are there new hours and someone to reach out to if I were looking to find more information? Thank you”
- The script is editable by anyone, would suggest we change that. (I almost edited it myself by mistake)
- They don't mention to the volunteers to keep doing this. I would emphasize the impact these volunteers are having in other people's lives. 
- Maybe tell the story about X that got her weekly food pantries from Y organization thanks to the volunteer that updated the info. 
- Say the number of people that rely on these updates.
- I realized some people said they would come back next week, should that be a different session? So that the recurring volunteers don't see the same onboarding presentation every week. 
- Have another time slot in the weekdays for doing the same cause that may have better outcomes from the gathered info. In Saturdays most orgs close. Or a slack channel to encourage volunteers to do the research and updating.

**Comment by ktjnyc** [comment]
Adding links for the user flows in pdf and slides 
[User flow PDF](https://drive.google.com/file/d/1g64nt3S0FgQDp2yHeugPEny481nrKh4R/view?usp=sharing)
[User flow slides](https://docs.google.com/presentation/d/1y6O7ghU-YmCD-oEJBBe2cDcz2cyy5HP1fAmYRP_ouJk/edit?usp=sharing)

**Comment by ktjnyc** [comment]
Found another [issue Jenny had created previously](https://github.com/hackforla/food-oasis/issues/858) with suggestions for ordering and freezing columns

**Comment by staceyrebekahscott** [comment]
@entrotech Moving to Questions/ In Review column. Links in Overview section go to old Drive/ Access Denied. Should this issue be revised and addressed, or is the original reason for the issue become outdated and issue can be closed?

**Comment by staceyrebekahscott** [comment]
Closing this issue as outdated. The last work on it was done in April 2021, the issues associated with it are closed, and many of the links to the docs give access denied messages.
