### ISSUE TITLE
Populate Neighborhood Field for Organizations

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#371]
### Overview
Upon completion of Issue #370, we will have the ability to associate each organization with a neighborhood (Neighborhood Council, in the case of the Cith of Los Angeles). This issue is to enhance the application to easily populate the the neighborhood field based on the organization address.

### Action Items

- [x] Identify an algorithm for determining which neighborhood an organization falls into based on it's latitude and longitude. This should be in javascript and could be executed from the client or the node server.
- [ ] Develop a way to run all the existing organizations through this algorithm to assign each organization to a neighborhood (if it has one).
- [x] Decide how if/how we want to implement assignment of new stakeholders to neighborhoods when a new organization is entered in the system (maybe piggyback on the "Get Coordinates" feature of the Organization Edit page to get the neightborhood at the same time?)

### Resources/Instructions
Ryan Swan from the 311 project promised me some sample python code for the algorithm, but I'm sure there are many approaches to this problem, and a google search should turn up some javascript methods that will work for us.

**Comment by entrotech** [comment]
Here is a short python program for converting lat/lon to neighborhood council from Ryan Swan on the 311 project:

[coord_binning.zip](https://github.com/hackforla/food-oasis/files/4600607/coord_binning.zip)

**Comment by StevenKitzes** [comment]
The Python code above relies on Python packages that perform the heavy lifting.  In order to parse shapefiles, and determine what regions of the shapefile certain points fall in, we will need to use equivalent JS libraries or roll our own.

Some resources I discovered that may come in handy:

- NPM package that claims to be able to parse shapefiles (haven't had a chance to test it yet): https://www.npmjs.com/package/shapefile

- StackOverflow topic on determining whether a point falls within a polygon (in cas- e we don't find a satisfactory JS package to do this for us): https://stackoverflow.com/questions/22521982/check-if-point-is-inside-a-polygon

Additional notes from my early readings: it seems like GeoJSON is the JS format of the data that goes in and out of shapefiles.  It appears to be a valid standard with a legit specification.  More information can be found here: https://geojson.org/

**Comment by entrotech** [comment]
PR #629 #633 #634
