### ISSUE TITLE
Investigate "Save Button Disabled" Bug on Organization Edit form

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#482]
### Overview
Shawn Sites and Jenny Mikesell have reported a bug on the Organzation Edit form where they have edited data, but the Save Progress button is not enabled. There is a known bug where minor edits to the business hours are not detected as a change and the Save Progress button is not enabled if that is the only change, but this seems to occur even when other fields have been edited.

### Action Items

- [ ] Work with these users or other volunteers to identify the circumstances under which this problem occcurs.
- [ ] Fix it.

**Comment by motorcykey** [comment]
Leaving a note for myself: initial investigation shows that this Boolean is returning true when editing any of the fields in each row on the Business Hours page (anything found in OpenTimeForm.js or OpenTimeInput.js):

https://github.com/hackforla/food-oasis/blob/develop/client/src/components/StakeholderEdit.js#L300

It looks like when we update the inputs, the `originalData.hours` property also gets updated. But the expectation should be that `originalData` would contain whatever data as what we loaded the page with (or saved the form with), and only the `values` object gets updated as we modify the fields.

I'll have to look further into this and how originalData is updated.

**Comment by motorcykey** [comment]
After another look, it seemed to be an issue with the nested object. When nested objects are copied, usually only their first layer gets copied unless they're deep copied. Any other layer (in this case, the `hours` properties) just gets a reference copied. So when we update `hours` it makes its way all the way back up to its original reference. This might explain why we're seeing `originalData.hours` the same as `values.hours` as soon as we're modifying the values.

Ideally, we'd want to make sure that `values` is created by deep copying `originalData, but since this is all handled using Formik, I'm not entirely sure how this gets done. I did play around with setting the `initialValues` param to some different things, but didn't have much success.

I've never used Formik before, but I'm eager to learn more about it. I've found documentation that it does work with nested Objects as well as guides to follow on how to properly get it working, but I suspect it'll take some time to learn about the library and walk through the guides.

If this fix is needed ASAP and another developer is familiar with Formik then I can always pick up something else. We can discuss more Thursday.

**Comment by entrotech** [comment]
This is not a super high priority, so we can hold off on fixing it til I can get around to it.

**Comment by Benbaillou** [comment]
Hi - can we label the size please?

**Comment by staceyrebekahscott** [comment]
Closing issue as outdated. 

Issue has been in the Icebox since Aug 2020. If it was still a problem, it would have been identified.
