### ISSUE TITLE
Implement a Share button for Food Seekers

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#684]
### Overview
A share button for food seekers would allow them to share the URL link of an organisation to a contact.
The goal is to increase user acquisition of new users by enabling referrals.

### Action Items

- [x] Work with user research team to identify a possible need from the user
- [x] Make wireframes with design team and identify possible solutions
- [x] Discuss the feasibility of the solutions with engineers
- [x] If feasible - create an MVP to be tested and define what a success looks like
- [x] Launch full product

**Comment by bbovenzi** [comment]
I can take this one.

For GoodWorkCafes we made most search criteria their own human-readable urls:
- Cafes in SF (map mode): https://goodworkcafes.com/cafe-map/cafes-in-san-francisco
- Cafes in SF (list mode): https://goodworkcafes.com/cafe-list/cafes-in-san-francisco
- A specific cafe in SF: https://goodworkcafes.com/cafe/precita-park-cafe-&-grill
- Cafes in the Mission Bay neighborhood: https://goodworkcafes.com/cafe-list/cafes-in-mission-bay

I would propose doing the more-or-less the same thing, along with a share button that would copy the url to clipboard.

Thoughts?

**Comment by fancyham** [comment]
How is this looking?  We have deep linking now which I think was a huge component of this.

Do we now have a share button?  Where does it live?

The browser share button, I think, works now, but that wouldn’t work for embedded FOLA (I think)

Perhaps we need a “share” or “copy url” button on each listing so that we support this function on embedded maps?

**Comment by staceyrebekahscott** [comment]
@VirginiaWu11 Following up on Bryan's questions in the comment above- please advise.

**Comment by fancyham** [comment]
Update:
We do now have deep linking working to link to a specific organization, and we do have a share button that works with the caveats below, so almost done with this issue.

The “share” button on each org’s details screen.:
![FOLA Design System – Figma](https://user-images.githubusercontent.com/3376957/186497470-025dc50f-9b2c-411e-b784-177aaa00e4fc.png)

which on iOS brings up the system share menu and depending on what option you choose, passes on the text: 
“My Friends House LA (My Friends House)
https://la.foodoasis.net/widget?latitude=34.0368201&longitude=-118.2414826&org=my_friends_house_la__(my_friends_house)&id=3062”

Two issues:
- [ ] Usability: The share button icon is not obvious — I’ve seen this on other projects where the 3-dot-< ‘share’ symbol isn’t recognized to mean ‘share’ by users, especially for iOS users.  It’s much more common on Android.
  - Can this icon be changed to text “Share” or something similar? @GigiUxR thoughts or recs for a clear share button label?

More ideas here: https://css-tricks.com/ux-considerations-for-web-sharing/
![share-button-collage png copy](https://user-images.githubusercontent.com/3376957/186500015-86761f44-aa9b-4b2e-b127-8c7308eae58f.jpeg)

- [ ] The text string sometimes drops the URL: 
  - On iOS, the share text doesn’t copy well (selecting ‘copy’) and the URL is lost.  I suspect it’s an issue with the carriage return between the org name and the URL, so could we try that text with a space instead of a carriage return and see how that works? @entrotech

**Comment by fancyham** [comment]
Corrected image in previous comment

**Comment by VirginiaWu11** [comment]
@fancyham Hey Bryan! Which share icon should we use? or are we happy with just text like the other buttons next to it?
<img width="379" alt="Screen Shot 2022-09-04 at 9 50 07 PM" src="https://user-images.githubusercontent.com/79432798/188344795-7f20f969-f017-480a-876e-d7fdd6230144.png">


_The text string sometimes drops the URL_ - regarding this, could you please provide an example/location which drops the URL, I want to recreate this on my end before trying out your suggestion.

Thanks!

**Comment by fancyham** [comment]
@VirginiaWu11, 

**For the share button**

I personally like the Share text because it's so clear, if we can fit it.  Or Share followed by an Arrow, perhaps?  

Maybe come up with a couple variations and we can ask the group?  and/or ask the group for examples of sharing buttons that they are most familiar with (perhaps in Slack, then post summary of results here)?

For example, I personally rarely use share buttons on the web page, instead preferring to use the system share button.  I do recognize and use perma-link icons once and a while when bookmarking or sending a link to a specific comment in a comment thread, but I suspect that's an advanced feature.

**For the "The text string sometimes drops the URL" part:**

The text that's currently shared when tapping the share button is something like:

Angelus Plaza an RAF community
https://foodoasis.la/organizations?latitude=34.05197&longitude=-118.24904&org=_angelus_plaza_an_raf_community&id=4976 

so the org name, carriage return, then the deep link URL.

So big caveat: I'm running some beta software, so this might be a bug but…

On an iOS device, try the "share" button on the org listing, then depending on if you choose to:
Copy link
Send as text message
Send as email
Add to Note

You will get different results — sometimes the org name is there, sometimes it's removed… I suspect it's because the text we're sending has multiple lines, and the different apps (copy, send as text message, email) all handle that text differently?  Or perhaps Apple is fetching the title of the web page?

One thing I definitely notice, though, on iOS is that our deep links to an org often turns into a URL chiclet/preview/unfurl that doesn't have the organization name — it just says "Food Oasis" — which is no good if someone is sharing links to several orgs.

I strongly suspect this is because Apple is fetching the title from the URL… and that title is  "Food Oasis", so the solution might be to
1) perhaps look at the text we're 'sharing' 
2) get the page title to update automatically when we're showing an organization's details, so when on the "Angelus Plaza an RAF community" org detail screen, the web page tab title might be "Angelus Plaza an RAF community - Food Oasis" or something like that.

**Comment by fancyham** [comment]
Hi, checking in on the progress of this issue.

Also:

Recently when trying the share button, a bunch of us found that on desktop browsers such as Chrome or Firefox, clicking the ‘share’ button doesn’t seem to do anything.

It’s actually coping the URL to the clipboard, but there’s no indication of this to the user.

Some possibilities to fix this:

1. Clicking the Share button changes the button state to “Copied to clipboard √” as seen on some websites

![IMG_0155](https://user-images.githubusercontent.com/3376957/199289786-6c7ae64d-0304-4018-9e1c-19d7b46239fd.jpeg)


2. Clicking the Share button displays a dialog showing the URL and an explicit ‘copy link’ button, and perhaps an ‘email this link’ button which uses a mailto: link to compose a new email.

![IMG_0151](https://user-images.githubusercontent.com/3376957/199288495-d161ed62-8bf5-4f7e-8db8-f02442b61226.jpeg)

**Comment by entrotech** [comment]
Here is what I get on Windows 11 with Chrome Browser when clicking on the Share button in devla.foodoasis.net:
![image](https://user-images.githubusercontent.com/9939032/201245166-6b5eb557-7070-4ae5-b69e-a417a3b21aec.png)
 
and on an Android Phone (Pixel 6), I get the expected share drawer at the bottom on the screen, and it copies the link to, e.g., gmail, as expected.  

Can we close this issue?

**Comment by fancyham** [comment]
Oh nice — I noticed these ‘share sheets’ are getting bigger on up-to-date devices… however, I think that on some browsers, it’s not obvious what happened:

For example, Firefox and Chrome (on Mojave OS X 10.14 from 4 years ago) don’t display a ‘share sheet’ like in your image above but does display a dark-grey nondescript toast.  It’s a small one in the lower left — very not-visible.  

![IMG_2638](https://user-images.githubusercontent.com/3376957/202987744-c0e3fc97-d380-41ba-8bbd-ed8f7f09c667.jpeg)

Could we perhaps make that toast more visible since it’s so important?  color, placement, etc.?  Maybe the message “copied to clipboard’ appears near the Share button that was just clicked.
