### ISSUE TITLE
Foodseeker full details of the organization

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#696]
As a food seeker, I want to be able to see all the information about a location, so I know before I arrive I’m eligible for service there. 

Acceptance Criteria

I need a modal window to display over the map or the list view with all the organization info

I need a close button to hide the info modal window when the food seeker click it

I need with the modal window pop up to display all the info in its current format

I need when the modal window displays for it to cover the full screen on the mobile device

See image
https://drive.google.com/file/d/1_EouR7-ramWlGL83lbEYyJPXdaF9ZRjT/view?usp=sharing

**Comment by bbovenzi** [comment]
We definitely need to update the bottom right Back button which can be hidden when scrolling.

**Comment by pageignited** [comment]
If you want to talk more in detail about this issue I would be happy too.

**Comment by DanielDev200** [comment]
Hi, I’m interested in taking this task, but have some questions.

First, it seems that the purpose of this task is to improve access to an organization’s information as well as fix some layout issues - is that correct?

I ask because as I use the application on my mobile and desktop device, it seems I can access all the information that I see in the wireframe, but getting to it is somewhat clunky and inconsistent (list view I get to the info in one click, map view takes two). Additionally there are layout issues, specifically with contact details overlapping with hours.

I also would like to clarify that there is no additional information being added into the view.

If my understanding is correct and nobody has already started on this task, I would like to take on this task.

**Comment by bbovenzi** [comment]
@DanielDev200 I believe you're correct. All the info is there, we just need to show it to the user better. Maybe @pageignited or @entrotech can elaborate.

I would say feel free to get started on those layout issues you see as those are clearly bugs.

**Comment by pageignited** [comment]
@DanielDev200 @bbovenzi Yes the content view is the same we did not make any changes to what we have now. This will be updated with the design team. Daniel, there is one issue with the location data overlapping that you pointed out.

How to reproduce the issue:
- When in the "list view" and you click on a location the content is overlapping in the full details screen. This seems not to be happening in a "map view". Can you investigate what the issue is on the front end display for a list view?
