### ISSUE TITLE
Look into compatibility or import/export to Open Referral format

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#751]
### Overview
There are a few standard for exchanging human services directory information among different systems. We need to decide what standards are worth pursuing and what level of support we should provide for the standards.

### Action Items
- [x] Arrange for meting with Greg Bloom, the principal of Open Referral
- [x] Evaluate the benefit or implementing as HSDS/HSDA for Food Oaisis as either a data provider and/or data consumer

### Resources/Instructions
https://docs.google.com/presentation/d/16zfaAy3_0No7EpYVyIA0PglUBSD6vsAgpyODAPvTBhA/edit#slide=id.ga3d864114c_0_170

**Comment by gigicobos** [comment]
**Meeting Recap 09/30 - Greg Bloom | Open Referral**:

We started with introductions and Greg asked what we wanted to know about OR. Below are points of what I understood:

- Greg explained the 3 models he is currently testing: Centralized open platform, data collaborative, and service registry. 
- We discussed the issues of having each organization handling their data and the issue that no organization thinks the data of other organizations is complete or accurate and maintaining data with volunteers is not sustainable. He talked about having 2 full time employees maintain data instead of volunteers.
- About 75% of the data from organizations overlap with the data of other organizations. About 25% is new data that would be very useful to other organizations if it's shared.
- There is an issue with data utility and one case that could work would be to work with a federated database across regions like in Ontario, the only place where this has been possible. He is currently working with the person who built this program in Ontario.
- Some organizations are still doubtful as they expect something perfect working from the beginning but he is aware it will be a long time until it actually works. There needs to be the right combination of policies, structure, and open-minded organizations.
- There is currently someone building products to help food pantries make information easy to collect and distribute, not sure if it was for profit.
- Greg commented on the importance of having shared and centralized data by highlighting that the amount of people that need food is a small fraction compared to all the people who look for related services.

Discussion after the call:
- Seems like Open Referral hasn't yet a proof of concept and it might need a lot of things to happen in order to work.
- We are able to adapt to the standard of Open Referral but at the moment we want to focus on the mission of FOLA and making the project sustainable. 
- We want to try different strategies, increase outreach, do some work with SEO, social media and marketing.

**Comment by gigicobos** [comment]
Adding comments from John's email to Nancy Beyda 10/12/21:

The meeting with Greg was interesting. Food Oasis currently both verifies our own data and presents it on our website.  If we were to adopt Greg's Open Referral (HSHDS) standards, it would open the door to allow us to interoperate with other systems in two ways:
1. We could supply data from our database to other websites or applications that are written to consume and/or search data in the Open Referral format. Greg did not seem to know of any potential consumers of our data. For example, the foodcyclela.org website is written in WordPress, and there would need to be a WordPress plug-in designed to consume Open Referral data and provide a suitable map and search capability.  The search capability of Open Referral data is pretty clunky for end-users and usually looks like what you see on 211la.org, where the search parameters include location and one or two other parameters that would mystify a food seeker. If there were other consumers that wanted to use our data in the Open Referral HSDS format, we would be interested in putting in the effort to provide it.

2. If another organization had good data and was willing to provide it to us at negligible cost, we could consume their data and add or replace our data with theirs. The obvious candidate for this is 211LA, since they do provide data in Open Referral format. However, they do not have the level of detail we already have, nor do they seem to keep their data updated very well, even though they have paid staff. This is probably because of the number of different types of organizations they are trying to track, while Food Oasis is currently only focused on Food Pantries and Meal Programs. Greg said that he has tried to work with 211LA, and even though 211LA has adopted the AIRS taxonomy for categorizing organizations and (I think the Open Referral HSDS standard for data exchange), they have been quite uncooperative with him.  What could benefit Food Oasis, though, is if we were to find an organization that is willing to share reliable, up-to-date referral data for related types of organizations that Food Oasis could add to our collection, such as referrals for legal services, farmers markets that accept SNAP, showers, haircuts, public restrooms or other related services. This would be pretty easy for us to add to Food Oasis to provide our users with additional resources.

**Comment by Benbaillou** [comment]
Hi - could we please size the project with a dedicated label. Thanks

**Comment by fancyham** [comment]
I believe we ended this as 'we aren't going to pursue this' right now.  

Should this issue be moved to the ice box or closed out as some sort of "WON'T FIX"?

**Comment by staceyrebekahscott** [comment]
Upon further review, this does not seem like a pursuit we want to focus on. It would rely too heavily on finding orgs that use the Open Referral concept, and it is unclear whether Food Oasis would benefit in any clear way. Closing issue.
