### ISSUE TITLE
Hide FoodOasis logo bar when mobile user scrolls up and lock filer bar to top 

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#756]
### Overview
We need the mobile interface to look professional when people go there, right now, there is a problem with the content in the second menu (meals, pantries and map) appearing under the logo and mobile menu bar which goes away when you scroll down and back up.  Define technical fix to keep this from happening

### Actions
- [ ] Discuss feasibility with engineering  team

### Resources
Landing page: https://github.com/hackforla/food-oasis/issues/756#issuecomment-1010253737
Map View: https://github.com/hackforla/food-oasis/issues/756#issuecomment-1010253409

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/149002119-15cf1c67-5366-4e05-93f0-409e753d17cc.png)

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/149002195-b4fc5aef-b60f-4bdc-85d2-480b0c7ddad6.png)

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/149002687-b96ddf77-9f00-4ae3-b6b4-b76ded728857.png)

**Comment by ryu-jieun** [comment]
Please see the attached video for more detail: 

https://user-images.githubusercontent.com/78619802/164552739-c72b22ed-280e-40fb-95cc-978b2d0ed7de.MP4

This issue appears on the Chrome browser on iPhone 11. 

This issue was found during the heuristic evaluation - #1114 

Reference: https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0

**Comment by itserindean** [comment]
I think this issue as described no longer repros. if I misunderstand, please reopen.
