### ISSUE TITLE
Review home page

### ISSUE THREAD

**Issue by bbovenzi** [hackforla/food-oasis#762]
Problem: Landing page provides no value to foodseekers. Just adds an extra click and page load before getting info they need

Solution: default the home page to `/organizations` and add a tutorial pop-up on first page view to provide any description necessary

**Comment by fancyham** [comment]
I had similar thoughts.

I created a prototype with some ideas for folks to play with and comment on:

The prototype: @entrotech
https://www.figma.com/proto/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2743%3A9714&viewport=392%2C251%2C0.11034877598285675&scaling=min-zoom

The designs:
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2743%3A7824

**Comment by ktjnyc** [comment]
Free phone service in LA:
8GB SIM Only Data Plan
 8GB LTE data,
 Unlimited talk,
 Unlimited global messaging every month.
6GB Standard Smartphone Data Plan
 6GB LTE data,
 FREE Smartphone*
 Free Unlimited Talk and Text every month

**Comment by fancyham** [comment]
While some Lifeline plans are generous with their data, many are not.  Also, many folks don't have Lifeline plans and are paying out of pocket which means that they may opt for lower-data plans.  

Lifeline phone service details:

"IMPORTANT NOTE: The plans of the various companies below can vary considerably. Some may give unlimited minutes, some unlimited texting, and **most now include up or 500 MB of mobile internet data (or more!)**. And the phone models can vary greatly as well, with some providing smartphones. We urge you to compare plans of all providers who serve your state."

https://www.obamaphone.com/obamaphone-providers

500MB of data is nothing nowadays. Many web pages are 2+ MB, so that's less than 250 web pages.  
https://www.google.com/search?q=average+web+page+mb

(our foodoasis.la initial map page is currently 1MB)

**Comment by fancyham** [comment]
This task should be closed or merged into an existing issue, perhaps https://github.com/hackforla/food-oasis/issues/862

**Comment by ktjnyc** [comment]
Thanks, @fancyham closing this via #862 and transferring the recent comments there.
