### ISSUE TITLE
Volunteer app: Add bounding box for food types

### ISSUE THREAD

**Issue by bbovenzi** [hackforla/food-oasis#786]
Add a border around food types to make it more clear that you need to confirm the selected food types. See image: 

![foodtypes](https://user-images.githubusercontent.com/4600967/101701718-12f2f980-3a45-11eb-98d5-250f9be1d1df.jpg)

**Comment by entrotech** [comment]
I think we need to discuss how this should really look.  The intent of the issue was to modify the visual appearance to make it more apparent that the "Confirm Food Types" checkbox applies to all of the controls for selecting food types, including the other six chackboxes, as well as the free-form Food Types text fiels.  Neither the mock-up above nor the impelementation in  PR #789 really does this. We also don't really have a good precendent from the first two pages of the wizard that would work well here.
