### ISSUE TITLE
Review and update personas

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#885]
### Dependencies
#955 

### Overview
We need to update our personas so that we are building the tools/pages that match our users.  

### Action Items

- [x] Review personas (none one record)
- [ ] Create new personas
- [ ] Provide comments on personas 
- [ ] Select & prioritize personas

### Resources/Instructions
[Hack for LA Guide for personas/user stories](https://docs.google.com/document/d/18Wmoe9n-GptmDe1FZWl_xmNqtH5dHk5z03nnp8_MATM/edit?usp=sharing)
[FOLA user stories/personas](https://github.com/hackforla/food-oasis/wiki/User-Stories)
[USC Food Insecurity Report](https://drive.google.com/file/d/17DHvE2xJQJb5VHF-B3i111czGOI09PuC/view)
[Current User Persona Research](https://docs.google.com/document/d/19CiBd11ukhrsNEdGcDZBbUAiGroGeCKgwLr21FYfHdU/edit)
[Draft Personas](https://docs.google.com/document/d/1uj-UVdTz1LVehaxjES1s5z7NCs_fYfz2AtQTHSD9sP8/edit?usp=sharing)

**Comment by ktjnyc** [comment]
I created a [copy of the personas](https://docs.google.com/document/d/1Wnkib3z26MzSlj-3hrvjMG_kcBHrCildPhSSAjO6_Sc/edit) so that we can provide comments

**Comment by ktjnyc** [comment]
Looks like what was linked previously was the guide on creating the user personas.  

Current personas exist here - https://github.com/hackforla/food-oasis/wiki/User-Stories

**Comment by ktjnyc** [comment]
Bryan asked Thy to provide some additional guidance from her experience.

**Comment by fancyham** [comment]
@wanderingspoon

**Comment by wanderingspoon** [comment]
I’m currently reading and aggregating research that addressing food insecurity and mobile tech use among vulnerable communities in CA.

**Comment by wanderingspoon** [comment]
Here's a document that brings together demographic information about food insecure households in California and US, along with some studies on mobile tech use in low-income communities.

I think we can use the data to create solid personas for now. These will need to be validated later, of course, but I think they can still be helpful in the meantime for design and development teams.

[Food Insecurity & Mobile Tech Use Among Low-Income Households: Distillation of Published Research](https://docs.google.com/document/d/1SN1n2ZZKf8AOhkQUFlEICNkagRuazDyzEcRpxUT0d4w/edit#)

**Comment by wanderingspoon** [comment]
Provisional action items, depending on discussion with larger team:
- [ ] Create template for personas based on design and development objectives
- [ ] Select and prioritize archetypes
- [ ] Flesh out archetypes with details (e.g. circumstances, problems, and desires)
- [ ] Present drafts to team
- [ ] Select 3-5 primary working personas, with 2-3 secondary for contingency or long-term
- [ ] Finalize personas
- [ ] Share out, discuss and document

Upon completion, potential next steps, depending on team needs
- [ ] Create user stories
- [ ] Sketch out user journeys
- [ ] Validate with user research

@nkiwan @ktjnyc

**Comment by wanderingspoon** [comment]
Could we add a parallel issue? @ktjnyc 

It would be ideal if, while Natalie and I work on the personas, that another team is coming up with the criteria which will be used for selecting and prioritizing them later, after we present them to all stakeholders. I would prefer strongly that those criteria are established and communicated out before we present. Or at least, very close together in time. @fancyham

Natalie and I will confer soon to clarify our soonest delivery date for the personas. We can also delay the presentation as needed to sync with creating the criteria. @nkiwan

**Comment by wanderingspoon** [comment]
Current persona team: Natalie Kwan, Thy Tran

**Working Task List**

PHASE 1
- [ ] Kick off meeting for persona team
- [ ] Schedule stand-up or milestone meetings for persona team
- [ ] Establish scope of work and deliverables
- [ ] Create template for persona sheets
- [ ] Divvy up work
- [ ] Commit to deadline and sketch timeline; share out with larger team

**Comment by wanderingspoon** [comment]
Not sure how to create dependencies? In order to ensure that we can later select and prioritize personas successfully. 

> Coordinate with design and development teams: prioritization of resources and objectives
> Coordinate with management and product teams: clarification of overall goals and criteria for selecting personas

Natalie and I will not need these to deliver the personas. But they're critical for progress afterward.

@fancyham @ktjnyc

**Comment by ktjnyc** [comment]
@wanderingspoon I'll create the parallel issue and link it here under dependencies at the top.

**Comment by nkiwan** [comment]
**Persona Task List Update**
 
- [ ] Create template for persona sheets
- [ ] Commit to deadline and sketch timeline; share out with larger team

Personas have been assigned
Expected timeline for deliverables: 4-6 weeks

Next steps are to build out assigned personas (with qualitative data from interviews if possible) and check in at weekly stand-ups.

**Comment by wanderingspoon** [comment]
Created script for 20-30 informational interview for professionals working with food insecure populations.
[https://docs.google.com/document/d/1MsavDa9JGKdeqmuonpFZhwno2BkKvqFv/edit](url)
Interviewed national director of food insecurity at federal gov't agency.

**Comment by wanderingspoon** [comment]
Natalie and I are leaning toward group profiles (e.g. single parents, seniors, case managers)  instead of individual personas (e.g. named, fictionalized). To us, the latter feel fragile, forced and less useful as we have not conducted user research for the details. Group profiles, while not conventional user personas, seem more robust as they'll be data-driven or supported by secondary sources.

We presented examples of both and asked the group about their preferences. After short discussion, consensus settled on group profiles. Later, once we have enough research on actual users, we can create specific, named personas.

[Examples of group profiles vs. individual personas](https://docs.google.com/presentation/d/1JgFyr-Pfnxo86iBwggsvlLcBI81Ehu26/edit#slide=id.p1)

@nkiwan

**Comment by wanderingspoon** [comment]
Some delay in presenting, as we lost files during the May 31 bug with Google Drive and still have not retrieved more recent notes during May. 

Have decided to move forward with documents from April.

**Comment by fancyham** [comment]
The current thinking on this (with feedback from @wanderingspoon) is that since we haven't done new research, that the document mentioned above should give us the best understanding of our users without the risk of making things up from whole cloth, or taking from news or publicity pieces (where stories are used to illustrate a larger narrative).

Please refer to this document to better understand food seekers in the Los Angeles area:
[Food Insecurity & Mobile Tech Use Among Low-Income Households: Distillation of Published Research](https://docs.google.com/document/d/1SN1n2ZZKf8AOhkQUFlEICNkagRuazDyzEcRpxUT0d4w/edit#)

A future project would be to interview actual food seekers, people helping food seekers.
