### ISSUE TITLE
Implement Volunteer Check-In/Check-Out feature.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#897]
### Overview
We need a way for Data Entry users to "Check In" and "Check Out". 

### Why

This would allow us to build features that can track volunteer hours, and allow a Volunteer Coordinator and/or administrator to see which volunteers are on-line during a training session or volunteer event. 

### Details

To start, it will just be a check-in/ check-out button on the Volunteer Dashboard and write to a table in the database for subsequent issues to expose in various ways.

### Action Items

- [ ] Create a login_session table in the database that has columns id (identity integer), tenant_id (integer foreign key to tenant table), login_id (integer foreign key to login table), start (a UTC datetime), stop (a UTC nullable datetime) columns, 
- [ ] Create a RESTful Web API routes, controller and service for the following operations:
  - [ ] GET entries from the table. This should probably be a parameterised query that allows getting records based on various search criteria, like login_id, tenant_id, start or end date range. Querying to find records where the end datetime is null will allow finding users who are currently checked in.
  - [ ] POST (Insert) would insert a record with a specified login_id, tenant_id and start datetime (the end datetime would be null when a user first checks in).
  - [ ] PUT (Update) would update the end datetime for the record with a particular id (or maybe combination of login_id and tenant_id) when the user is "checking out".
- [ ] Test the Web API from Postman or a similar tool to verify that they work correctly.
- [ ] Add few controls to the Volunteer Dashboard that allows the user to check in, check out, and maybe see an indication of when they checked in.
- [ ] Figure out how to handle situations where a user forgets to check-out.
- [ ]

**Comment by fancyham** [comment]
I think a big reason we're doing this is so that our volunteer coordinator can easily tally up the hours someone has worked on the site.  

Are there ways to get a rough estimate instead of being totally accurate?

For example, perhaps the server can track the last time a page was served to a user, or per when a log-in cookie expires?

That way we can create something approximate like:
"2021-08-03 14:30 - username - Logged out automatically 15 minutes after last page access.  Total time logged in was approximately 51 minutes"

And this record could be in the log shown in #835 (and perhaps the same log as in #834 )

**Comment by gigicobos** [comment]
- Triggered by login
- Record last active time
- Show how many hours between login to last active time

This feature could be used for the sessions as well. If you look at the last people who log in on the day of the session, the admin can have an idea of who is attending the session.

**Comment by staceyrebekahscott** [comment]
@entrotech @rylantalerico Following up on the discussion during the meeting on this issue, is this also similar to issue #379 and if so can these issues be merged?

**Comment by staceyrebekahscott** [comment]
Moving this to Backlog in Product board, for assessment. As we think about a Volunteer PM role, we want to see if this process is something we still need. This issue originated in March 2021 and needs reevaluation.

**Comment by staceyrebekahscott** [comment]
This issue seems to be predicated on working with a volunteer coordinator at either LA Works or some other volunteer recruiting organization. Since we are currently working with UCLA students, @itserindean Do you think we still need this? Is there another way you are tracking the student volunteers so they are meeting their requirements? 

If so, I think we can close this issue.

**Comment by itserindean** [comment]
I track submissions/week instead of hour. Since we're not currently working with LA works at the moment. closing as not planned.

**Comment by farahrobleh** [comment]
[Time card dashboard example from internship team](https://lookerstudio.google.com/reporting/9b5539d5-6c2b-4b7e-af46-7351d41151d5/page/7ejxC) built in Looker
