### ISSUE TITLE
Usability of Map Pin Clustering

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#907]
### Overview
For Issue #761, we implemented "clustering" of map pins when there are a number of map pins with overlapping icons because they are close together. It's not clear that this is desireable, so I'm proposing that we create an experimental branch of the project that undoes the clustering and have an appropriate group of people examine the two implementations and decide whether clustering is desireable, and what adjustments need to be made to the map behavior to improve usability.

### Action Items
- [x] create branch that "undoes" the pin clustering.
- [x] present to project team for feedback and suggestions.
- [x] Make changes to app accordingly and create follow-up issues.

### Resources/Instructions

Docs: https://docs.mapbox.com/mapbox-gl-js/example/cluster/

[Issue for clustering research ](https://github.com/hackforla/food-oasis/issues/869)

**Comment by entrotech** [comment]
Deployed to https://devla.foodoasis.la

**Comment by fancyham** [comment]
Some of the issues with clustering on the current site are:
- Tapping a location on the map zooms out and clusters, obscuring the location of the thing you tapped.
- Clustering hides useful location information and clusters start at too low a zoom level (too close to street level)
- Clustering obscures density of locations in a neighborhood (because clustered pin location is arbitrary)

**Comment by entrotech** [comment]
On 4/1/21 the group agreed that eliminating the pin clustering was a good idea.  Other observation led to follow-up issue #926, and #929

**Comment by fancyham** [comment]
On 4/1/21, the group chose to try Option C (no separate landing page).  

Programmers: UX 'documentation' is in the Figma file, but let me know if you need a more explicit spec.
