### ISSUE TITLE
Modify background image system on landing page

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#939]
### Overview
This is part of #862 

The current landing page has a background image that rotates among several very large high resolugion images of produce. This consumes a lot of bandwidth, impacting performance in low-bandwidth environments. We want to change the background to a single low-resolution image of a map, indicating to the user that the appication will show them a map of places to get free food.

### Action Items
- [x] Remove the current logic for randomly swapping background images on the home page
- [x] Create a low-resolution (maybe washed-out) map image to use for a static background. This could be obtained as a screen-shot from the current map page (with or without markers)
- [x] Replace the background image on the landing page with the new map background.
- [ ] Implement and push live

### Resources/Instructions
This Figma file (the Page called "2020-03 Landing page flow experiment") Option B shows roughly what we are aiming for.
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2743%3A7824

**Comment by fancyham** [comment]
Single background is working on dev site, but not yet made public at this moment.

This issue is part of solving #862

**Comment by fancyham** [comment]
Not yet finished, so reopening issue — changing background image to a better map image.

——

Okay, an update!  I’ve gotten some good feedback and we’re 90% to a final background. 

Basically, we’re looking at a single screenshot of the zoomed-out active geographic area for each food oasis instance, no markers, blurred but no dimming. 

This helps folks feel included and encouraged, even if they’re on the outskirts of the service area (e.g. such as over the hills to the north of LA)

Here’s the latest mockups and you can see the evolution. Newest mock-ups are in front: https://docs.google.com/presentation/d/1OJZ4ZU6dsmRDjakxiGIZJrH-KrGtwUk9GYxWlBuMJVo/edit#slide=id.ge16fc0cbc8_0_0

One twist:

We have multiple regions coming online soon in addition to LA: adding Hawaii and McKinney, TX — and we’d need to have individual backgrounds for each region.  Will that be possible to do? (edited) 

Actually, I think the multi-tenant support thing is a separate issue — I think the goal will be to get this working with the LA background only for now.  Stretch goal would be support for random background images — still just for LA (for future use).

———

dking1342:

I brought this up yesterday in the dev meeting. After our discussion, the concept of having different backgrounds for different tenant ids is possible. I would need the images for each region. I saw what you have put in the post. If those are the final images then I can include them in code. I'm assuming that those images are low-res with a small file size as that was one of the original goals.

If we will only go with the LA image for now then I can make the code ready if we want to move ahead with the other regions. It would be there in case we want to move ahead with the different images for different regions.

**Comment by fancyham** [comment]
@dking1342, Moving forward with the designs as discussed: 

I created some images for LA, and Hawaii and McKinney, TX attached here — both originals in JPG format (I have PNGs if you need them) and a blurred version.  Feel free to compress further.

**Unblurred at retina resolution**
![Food Oasis - Hawaii background](https://user-images.githubusercontent.com/3376957/127582990-b36e8f88-9b2a-4e9a-8d2e-6521645c1be7.jpg)
![Food Oasis - Los Angeles Background](https://user-images.githubusercontent.com/3376957/127582991-bb5349f0-f36a-46b7-929e-244e93816360.jpg)
![Food Oasis - McKinney TX background](https://user-images.githubusercontent.com/3376957/127582994-5088d885-5678-4ed9-9f77-d13ae4d9e62b.jpg)

**Blurred (Gaussian, 4px)**
![Food Oasis - Hawaii background - Gaussian blurred 4px](https://user-images.githubusercontent.com/3376957/127582996-01817fb1-a2df-49be-b6e9-048c565fa014.jpg)
![Food Oasis - Los Angeles Background  - Gaussian blurred 4px](https://user-images.githubusercontent.com/3376957/127582997-1a67d6fb-92d4-496c-89d5-a068566c70cf.jpg)
![Food Oasis - McKinney TX background - Gaussian blurred 4px](https://user-images.githubusercontent.com/3376957/127582998-80f95f40-41a3-4024-ae42-fe38eafec47d.jpg)

**Comment by fancyham** [comment]
Please use the blurred maps.  I've provided the sharp originals in case you need them for any reason.

**Comment by dking1342** [comment]
The background images provided have been included in the branch dk-backgroundimages. The files have been compressed to approximately 50kb respectively. The background image has been synced to the tenantId found in the helper/Configuration file. There was not a background image for Oregon so I put the image of LA there instead. If there is an image for Oregon then please provide.

**Comment by fancyham** [comment]
Oh, we’re doing Oregon, too?  @entrotech could you tell me what city/town and I’ll make a screenshot?

For future images: 
Go to our map provider (MapBox?), find the target service area, zoom out so that the entire service area will be in view on a laptop screen.  Take a screenshot.  Gaussian blur it with a 4px radius.

I used the entire service area so that even pantries on the outskirts of town are in view (such as over the hills to the north of LA), helping folks in that area realize that they can find services there, and it’s not just the urbanized areas.  

“If in doubt, zoom out”

What I did to create the source images:
1) On an Apple laptop with a retina (high PPI) computer screen, I set the zoom factor to ‘smallest text’ (System Preferences > Displays > Scaled > Show more content)
2) I went to foodoasis.la, manually navigated to the target region’s service area
3) Used browsers’ s developer web inspector to turn off everything on the web page except the map.
4) Take screenshot
5) I used Pixelmator Pro to Gaussian blur 4px, but any app should be able to do this.

**Comment by fancyham** [comment]
@dking1342 , Hey there, just heard the Oregon isn't necessary, so just the three areas for now are all that's needed.

**Comment by dking1342** [comment]
Ok... I have removed the option for Oregon. Now it only has options for LA, HI and TX.

**Comment by fancyham** [comment]
I noticed a bug — possibly a CSS issue? 

On Safari on Mac and iPad, the Hawaii and LA map https://devhi.foodoasis.net appears initially uncentered horizontally as well as seems locked to the left edge when resizing the window (rather than keeping centered).  

Vertically, it seems to work fine, though.

![Food Oasis - misaligned background](https://user-images.githubusercontent.com/3376957/130166505-dadd5ac5-9762-42a9-824f-7ae31e21b4ad.png)

**Comment by dking1342** [comment]
Thanks for bringing this up Bryan. You are correct, it was an issue with the CSS. I added a background position of center that takes care of this. I will create a pull request to have this rectified.
