### ISSUE TITLE
Scrape data from Food Pantries web site into table called load_food_pantries (foodpantries.org)

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#95]
Trigger the import from a web api endpoint in the node app using node js and a scraping library like cheerio.

### Resources
create a folder inside this [folder](https://drive.google.com/drive/u/1/folders/15V2rV3aTLiA16juUUPlUmfsi-t2zW-vc) and place the .csv file for this scrape in it.

**Comment by chrislopez28** [comment]
Scraped website for all food pantries in California using Python (Requests, BeautifulSoup, and Selenium). Here is latest csv: https://github.com/chrislopez28/webscraping-examples/blob/master/foodpantries_scrape_2020-02-07.csv

Also started a Jupyter Notebook that could be used as a reference for scraping: https://github.com/chrislopez28/webscraping-examples/blob/master/webscraping-example.ipynb

Next Steps:
* Update scraper so that it only scrapes Los Angeles County food pantries.
* Go through each column of scraped data csv to check for errors / issues

**Comment by chrislopez28** [comment]
Uploaded scrape from 2020-02-09 to [google drive](https://drive.google.com/drive/u/0/folders/15V2rV3aTLiA16juUUPlUmfsi-t2zW-vc).

178 Pantry Entries

Fields: 
* Name
* Description (includes hours)
* Street Address
* State
* City
* Telephone
* Zip Code
