### ISSUE TITLE
Analytics: Add Track for Map Pin Clicks With Stormly

### ISSUE THREAD

**Issue by pageignited** [hackforla/food-oasis#950]
For the marker tracking, I found on the OpenStreetMap API (https://wiki.openstreetmap.org/wiki/Marker_API) a way that allows you to handle a market click, so basically a Stormly track event can be triggered from there:

marker.attachEvent( 'click', function() {
    infobox.open(map, this);
    window.stormly.event("view_organization", {organizationName: "Org ABC"});
});

**Comment by pageignited** [comment]
@entrotech When you can add this to Stormly this would be great, so we can use this as an event for conversion

**Comment by entrotech** [comment]
Since clicking on a map pin causes the Organization Detail Panel to be displayed, this would be raised every time the viewDetail event is raised, and include the same information id: (the organization unique id), name: (the orgnization name), so it is redundant. I'm going to add it anyway, since there might be an edge case or two I can't think of at the moment.

**Comment by entrotech** [comment]
I'm calling the new event "selectOrganization", since it gets triggered by either mechanism we have for selecting and organization: Clicking on a Map pin, or selecting an organization from the results list.  This has been deployed to the development environment, so you can try it out by exercising the site at devla.foodoasis.net
