### ISSUE TITLE
Bug: Some MacBooks have trouble with showing details?

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#958]
### Overview
John had a friend, Katie Receinos 20 y.o. bilingual college student take a look at the app to do a quick review of the experience and make suggestions. She found that on a Mac "desktop", the Details button or clicking on the map marker did not see to show the Organization Details panel.  This might be related to another problem Hannah Zulueta reported where the Organization preview panel did not show, as it was scrolled off the bottom of the screeen on IOS devices.

### Action Items
- [ ] See if anyone else can replicate the problem.
- [ ] Implement fix

**Comment by ktjnyc** [comment]
I tried on macbook and clicking on map marker worked fine for me.

**Comment by fancyham** [comment]
Wasn't able to replicate where the Organizations panel was missing completely, but at certain screen sizes / content, it's not obvious that the Org Details panel can be scrolled due to Apple's default for scrollbars and where our back button is:

<img width="1138" alt="Screen Shot 2021-09-02 at 2 27 30 PM" src="https://user-images.githubusercontent.com/3376957/131932851-2af03093-df82-4f7c-9266-3253d9282f71.png">

<img width="763" alt="Screen Shot 2021-09-02 at 2 27 38 PM" src="https://user-images.githubusercontent.com/3376957/131932853-faf658bf-5e5a-492f-870f-e95dfad67dda.png">

Suggest turning on scroll bar ON for Safari:

There's some CSS to display the scrollbar (when scrolling is possible) — can we try this?
https://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar

**Comment by entrotech** [comment]
We don't seem to be able to replicate this problem now.
