### ISSUE TITLE
Experiment with creating a widget to embed Food Oasis in a web site

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#962]
### Overview
We have had several requests to provide a Food Oasis widget that could be embedded in an external organization's web site. Explore the options and implications

### Action Items
- [x] Mock up how Food Oasis would appear on other sites
  - What branding appears?
    - Some sites / partners may want to highlight their specific locations as well as show all locations.  How would that work?
  - What does the initial screen look like?  (how to specify the starting location of the map?)
  - How can user open our full site for more screen real estate?
- [x] Look into the functionality provided by an IFrame or other implementation.
  - Can the behavior be tailored to the site by customizing the query, allowing some styling, etc.?
  - How can this be linked to attribute Food Oasis and re-direct to Food Oasis properly
- [x] How can we design to work with the Mapbox license agreement to avoid absorbing the charges incurred on the host site by mapbox requests?
- [x] Can we limit the number of map calls (which cost money) per embedded site so that we don't go broke hosting maps on other sites.
- [x] Can we generate a static snapshot (ideally hyperlinked) map that links to our site for cost efficiency that can be put on external sites.

### Resources/Instructions
Requests have been made by
Julia Blanton (Food Oasis Santa Barbara)
Nancy Beyda (Food Cycle LA)

**Comment by entrotech** [comment]
Created a wiki page that shows how to embed the widget in an HTML page [here](https://github.com/hackforla/food-oasis/wiki/Embedding-Food-Oasis-in-Your-Web-Site)


![image](https://user-images.githubusercontent.com/9939032/139506679-5521701d-30df-4dd2-a83f-77b3de6aaf09.png)

**Comment by fancyham** [comment]
I think this issue was closed automatically by a robot by mistake so reopening

**Comment by fancyham** [comment]
I tried embedding it in a generic web page (I grabbed the code from  https://github.com/hackforla/food-oasis/wiki/Embedding-Food-Oasis-in-Your-Web-Site ) and I set the height to 400 because 100% gave me a short letterbox-shaped iframe in my case..

For me, it was a little strange: after a long pause, it displayed the FO logo at the top, the hamburger menu, but was blank elsewhere.

fancyham.com/foodoasis.html

![Screen Shot 2021-10-28 at 4 47 57 PM](https://user-images.githubusercontent.com/3376957/139365498-77d2717b-5164-4236-86e4-5058ea1daf1b.jpg)

I wonder if we could/should have a target GPS lat/long as an argument for the URL to automatically bring up a map centered on a location?

**Comment by fancyham** [comment]
Embedding — things we want before releasing?
- [ ] Very narrow devices with iFrames in it
    - [ ] Stacking of buttons on very narrow buttons
    - [ ] Bottom row gets crammed up
- [ ] GPS button doesn’t work
- [ ] Want to specify default location and filter

Soon/Stretch?
- [ ] Tagging with filtering down to just those items

**Comment by fancyham** [comment]
I believe this is completed — we’re working on refinements like a nicer footer and special features as requested by neighborhood councils right now.
