### ISSUE TITLE
UX Volunteer User Testing for Volunteer Dashboard Changes

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#968]
### Overview
We need to conduct user testing on the wireframes so that we can validate the proposed changes to the volunteer dashboard.  

### Action Items

- [ ] Katie has the names/contact info of the volunteers that agreed to assist with the review
- [ ] Schedule time with each user for testing of the prototype

### Resources/Instructions
[Figma - Volunteer Dashboard mockup](https://www.figma.com/file/KZbof1x83FOvw4Jfc99EIf/Food-Oasis-Dashboards?node-id=0%3A1) for design changes

**Comment by gigicobos** [comment]
Figma file is linked to Organization Form design.

**Comment by staceyrebekahscott** [comment]
Overview references team members no longer involved in the project. I believe we can assume that the volunteer list being referenced is also out of date, given this issue was created in Aug 2021. 

A sub-project created by Briel appears to be doing something similar with current data. Closing this issue as not planned. 

@GigiUxR Can you confirm the assessment above is accurate? If so, this will confirm this issue has been correctly closed.
