### ISSUE TITLE
Look into AIRS https://www.airs.org/i4a/pages/index.cfm?pageid=1

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#97]
### Summary
This is a standards organization for standardizing the format of and exchanging information about "Community Information and Referral". Should food-oasis adhere to their standards and/or seek to become an accredited member of the association and a provider of or consumer of referral information?

### Resources
- AIRES Standards (page 12 on): https://www.airs.org/files/public/AIRS_Standards_8_0.pdf
- AIRES Tools: https://www.airs.org/i4a/pages/index.cfm?pageid=3363

**Comment by Jbarib** [comment]
Updates - 

AIRES Standards (page 12 on)	https://www.airs.org/files/public/AIRS_Standards_8_0.pdf
AIRES Tools:	https://www.airs.org/i4a/pages/index.cfm?pageid=3363

Next, I plan on matching the Taxonomy here: [https://211taxonomy.org/search/keyword-results?keyword=food] with our database field names.

**Comment by Jbarib** [comment]
Also, these https://211taxonomy.org/search/keyword-results?keyword=food for good codes

**Comment by Jbarib** [comment]
Here are the current data fields we are collecting by phone:

Name
Description of organization
Parent Organization
Address
City
State
Zip
Latitude
Longitude
Hours
Phone number
E-mail address
Website
Items
Services
Notes
Eligibility / Requirements
Social media
Facebook
Twitter
Pinterest
Linkedin
Admin notes

Here are a few potential extra fields that may be helpful to include, but are not in the original database:

Type of Food
Refrigeration needed
Manager Contact / Regional Contact if chain
Bilingual
ADA accessible
*this is an ongoing list

**Comment by Jbarib** [comment]
Additional helpful information from the AIRES:

What type of information?

- We are seeking to create an up-to-date online resource database that contains information about available community resources including details about the services provided and the conditions under which they are available.

- The database supports the inquirer’s right to accurate, consistent, comprehensive and unbiased information and the ability of the database to be a non-partisan, non-ideological and impartial information source for available nonprofit, government and for-profit services that meet the inclusion/exclusion criteria.

- We should develop criteria for the inclusion or exclusion of the different food assistance programs from the County in the resource database. The criteria should be uniformly applied and available so that staff and the public are aware of the scope and limitations of the database.

**Comment by ExperimentsInHonesty** [comment]
Add appropriate links to a Resources wiki page.

**Comment by ExperimentsInHonesty** [comment]
@Jbarib Please provide update:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@entrotech said As Is state = not using the standard.  But we could potentially standardize on it ,in the future and 211 uses the AIRES standard.  Or we might need to create an ability to import or export from AIRES.
